// Open Fufu Official-AI Baseline and character configuration.
//
// DESIGN-TIME SOURCE OF TRUTH.
// This file owns the exact concrete CharacterProfile mappings used by the
// Difficulty-0 Baseline and the 20 Official character presets.
//
// Difficulty, display/source metadata, Echo rewards, and allowed-Origin pools
// remain owned by OFFICIAL_AI_PRESETS.md and are intentionally not duplicated
// here. Gameplay mechanics and Origin mechanics remain owned by their own
// canonical rule/configuration sources.
//
// Character batches are appended to this single file. Do not create range or
// batch shards.

const ALL_GOAL_RULE_SETS = [
  "CORE_SURVIVAL",
  "CORE_EXPANSION",
  "CORE_ECONOMY",
  "CORE_INFRASTRUCTURE",
  "CORE_DEFENSE",
  "CORE_COUNTER_RESPONSE",
  "CORE_LAND_WAR",
  "CORE_ARMOR",
  "CORE_NAVAL",
  "CORE_AMPHIBIOUS",
  "CORE_STRATEGIC_WEAPONS",
  "CORE_OBSERVATION",
  "CORE_TEAM_SUPPORT",
] as const;

export const OFFICIAL_AI_BASELINE_CHARACTER_PROFILE = {
  id: "BASELINE_D0",
  evaluators: {
    territory: "LOCAL",
    economy: "BUDGET",
    opponent: "NONE",
    forecast: "IMMEDIATE",
    threat: "IMMEDIATE",
    opportunity: "OBVIOUS",
  },
  planners: {
    expansion: "NEAREST",
    landWar: "DIRECT",
    defense: "EVEN",
    counterResponse: "SIMPLE",
    retreat: "EMERGENCY",
    spending: "BASIC",
    infrastructure: "USEFUL",
    upgrade: "AFFORDABLE",
    armor: "LOCAL",
    naval: "LOCAL",
    amphibious: "BASIC",
    strategicWeapons: "OBVIOUS_TARGET",
    observation: "COVERAGE",
    team: "BASIC",
    spawn: "SAFE",
    spawnReconsider: "STATIC",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      SURVIVE: "REQUIRE",
      STABILIZE: "PREFER",
      DEFEND: "PREFER",
      REPEL: "PREFER",
      SACRIFICE: "DISLIKE",
    },
    motives: {
      SURVIVAL: "PREFER",
      PRESERVATION: "PREFER",
    },
    resourceAttitudes: {
      POPULATION: "CONSERVE",
      FFY: "SPEND",
      TERRITORY: "TRADE",
      INFRASTRUCTURE: "CONSERVE",
      ARMOR: "CONSERVE",
      NAVAL_ASSETS: "CONSERVE",
      STRATEGIC_WEAPON_CHARGES: "SPEND",
      ALLY_POSITION: "TRADE",
    },
    conditionalRules: [],
    customHooks: [],
  },
  goalGenerator: { ruleSets: ALL_GOAL_RULE_SETS, customRules: [] },
  arbiter: {
    kind: "SIMPLE_PRIORITY",
    maxPrimary: 1,
    maxSecondary: 0,
    maxBackground: 1,
    defaultResourcePosture: "BALANCED",
    customRules: [],
    customHooks: [],
  },
  persistence: { kind: "REACTIVE", temperament: "FLEXIBLE", rules: [], hooks: [] },
  expression: { defaultLeeway: "STRICT", rules: [], hooks: [] },
  originAdaptation: {},
  fidelity: {
    rules: [],
    customChecks: ["BASELINE_GENERIC_NO_CHARACTER_SIGNATURE"],
  },
} as const;

const THORFINN_KARLSEFNI = {
  id: "THORFINN_KARLSEFNI",
  evaluators: {
    territory: "OPERATIONAL",
    economy: "RETURN_AWARE",
    opponent: "BEHAVIOR_HISTORY",
    forecast: "SHORT_HORIZON",
    threat: "OPERATIONAL",
    opportunity: "OPERATIONAL",
  },
  planners: {
    expansion: "TERRAIN_AWARE",
    landWar: "OPERATIONAL",
    defense: "VALUE_AWARE",
    counterResponse: "EXCHANGE_AWARE",
    retreat: "DEFENSIBLE",
    spending: "PRIORITY",
    infrastructure: "NETWORK_AWARE",
    upgrade: "VALUE",
    armor: "OPERATIONAL",
    naval: "LOCAL",
    amphibious: "OPPORTUNITY",
    strategicWeapons: "OPERATIONAL",
    observation: "THREAT_FOCUSED",
    team: "OBJECTIVE",
    spawn: "TERRAIN_AWARE",
    spawnReconsider: "THREAT_AWARE",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      SURVIVE: "REQUIRE",
      STABILIZE: "PREFER",
      EXPAND: "PREFER",
      DEFEND: "REQUIRE",
      WITHDRAW: "PREFER",
      COUNTER: "PREFER",
      REPEL: "REQUIRE",
      RETALIATE: "PREFER",
      RAID: "DISLIKE",
      BREAKTHROUGH: "DISLIKE",
      ELIMINATE: "DISLIKE",
    },
    motives: {
      SURVIVAL: "PREFER",
      PRESERVATION: "REQUIRE",
      SECURITY: "PREFER",
      STABILITY: "PREFER",
      RETALIATION: "PREFER",
      PUNISHMENT: "DISLIKE",
      DOMINANCE: "DISLIKE",
      ELIMINATION: "DISLIKE",
      ALLY_SUPPORT: "PREFER",
      OPPORTUNISM: "DISLIKE",
    },
    resourceAttitudes: {
      POPULATION: "PROTECT",
      FFY: "SPEND",
      TERRITORY: "TRADE",
      INFRASTRUCTURE: "CONSERVE",
      ARMOR: "CONSERVE",
      NAVAL_ASSETS: "CONSERVE",
      STRATEGIC_WEAPON_CHARGES: "CONSERVE",
      ALLY_POSITION: "PROTECT",
    },
    conditionalRules: [
      "THORFINN_FORBID_INNOCENT_HOSTILITY",
      "THORFINN_REMEMBER_SELF_OR_ALLY_AGGRESSORS",
      "THORFINN_SETTLED_CONFLICT_DEESCALATION",
    ],
    customHooks: ["THORFINN_AGGRESSOR_MEMORY"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: [
      "THORFINN_AGGRESSOR_GATED_HOSTILITY_GOALS",
      "THORFINN_RARE_REMEMBERED_AGGRESSOR_REENGAGEMENT",
    ],
  },
  arbiter: {
    kind: "CONTEXTUAL",
    maxPrimary: 1,
    maxSecondary: 2,
    maxBackground: 2,
    defaultResourcePosture: "CAUTIOUS",
    customRules: [
      "THORFINN_INNOCENT_HOSTILITY_HARD_REJECT",
      "THORFINN_RETALIATION_SECURITY_PRIORITY",
    ],
    customHooks: [],
  },
  persistence: {
    kind: "CONTEXTUAL",
    temperament: "STEADY",
    rules: [
      "THORFINN_RETALIATE_UNTIL_SECURE",
      "THORFINN_DEESCALATE_AFTER_SETTLEMENT",
    ],
    hooks: [],
  },
  expression: {
    defaultLeeway: "MODERATE",
    rules: [
      { trait: "LOW_CASUALTY", preference: "SIGNATURE", leeway: "WIDE" },
      { trait: "PATIENT", preference: "STRONGLY_LIKE" },
      { trait: "COMPACT_BORDER", preference: "LIKE" },
      { trait: "NATURAL_BARRIER", preference: "LIKE" },
      { trait: "LOW_EXPOSURE", preference: "STRONGLY_LIKE" },
      { trait: "DEFENSIBLE_SPAWN", preference: "LIKE" },
    ],
    hooks: [],
  },
  originAdaptation: {
    themes: {
      FORCE_PRESERVATION: "REQUIRE",
      FORTIFICATION: "PREFER",
      GROWTH: "PREFER",
      EXPANSION: "PREFER",
      SACRIFICE: "DISLIKE",
      DECISIVE_FORCE: "DISLIKE",
      ESCALATION: "DISLIKE",
    },
    affordances: {
      PRESERVE_FORCE: "REQUIRE",
      TRADE_GROUND_FOR_CASUALTIES: "PREFER",
      LURE_OVEREXTENSION: "PREFER",
      RETALIATE_EFFICIENTLY: "PREFER",
      HOLD_GROUND: "PREFER",
      CREATE_BREAKTHROUGH: "DISLIKE",
      FORCE_ENEMY_RESPONSE: "DISLIKE",
    },
    cautions: {
      OVEREXTENSION_RISK: "AVOID",
      EXPENSIVE_FAILURE: "AVOID",
      SPLIT_FRONT_RISK: "RESPECT",
      ISOLATED_CORE_RISK: "AVOID",
      REQUIRES_GIVING_GROUND: "TOLERATE",
    },
    hooks: {
      signalInterpretation: ["THORFINN_ORIGIN_PRESERVATION_INTERPRETATION"],
      goalGeneration: ["THORFINN_ORIGIN_AGGRESSOR_GATING"],
      arbitration: ["THORFINN_ORIGIN_NONAGGRESSION_ARBITRATION"],
      persistence: ["THORFINN_ORIGIN_DEESCALATION"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "VERY_LOW" },
      { axis: "RETALIATION", expectation: "VERY_HIGH" },
      { axis: "POPULATION_PRESERVATION", expectation: "VERY_HIGH" },
      { axis: "TERRITORIAL_RISK", expectation: "LOW" },
      { axis: "WITHDRAWAL", expectation: "HIGH" },
      { axis: "SACRIFICE", expectation: "LOW" },
      { axis: "PLAN_PERSISTENCE", expectation: "HIGH" },
      { axis: "OPPORTUNISM", expectation: "LOW" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "NORMAL" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "NORMAL" },
      { axis: "ALLY_SUPPORT", expectation: "HIGH" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "LOW" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "LOW" },
      { axis: "NAVAL_USAGE", expectation: "LOW" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "LOW" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "VERY_HIGH" },
    ],
    customChecks: [
      "THORFINN_NEVER_ATTACKS_INNOCENT_FACTION",
      "THORFINN_REMEMBERS_SELF_AND_ALLY_AGGRESSORS",
      "THORFINN_POST_SETTLEMENT_REENGAGEMENT_IS_RARE",
      "THORFINN_RETALIATION_REMAINS_CHARACTERFUL",
    ],
  },
} as const;

const ASKELADD = {
  id: "ASKELADD",
  evaluators: {
    territory: "STRATEGIC_GEOMETRY",
    economy: "STRATEGIC",
    opponent: "ADAPTIVE",
    forecast: "SCENARIO",
    threat: "STRATEGIC_PREDICTIVE",
    opportunity: "STRATEGIC",
  },
  planners: {
    expansion: "STRATEGIC",
    landWar: "MULTI_FRONT_STRATEGIC",
    defense: "PREDICTIVE",
    counterResponse: "STRATEGIC",
    retreat: "STRATEGIC_SACRIFICE",
    spending: "OPPORTUNITY_COST",
    infrastructure: "STRATEGIC_OPTIMIZER",
    upgrade: "STRATEGIC_TIMING",
    armor: "STRATEGIC",
    naval: "STRATEGIC",
    amphibious: "STRATEGIC",
    strategicWeapons: "STRATEGIC",
    observation: "STRATEGIC_INFORMATION",
    team: "STRATEGIC",
    spawn: "STRATEGIC",
    spawnReconsider: "ADVERSARIAL",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      WEAKEN: "PREFER",
      RAID: "REQUIRE",
      PRESSURE: "PREFER",
      BREAKTHROUGH: "PREFER",
      SACRIFICE: "PREFER",
      WITHDRAW: "PREFER",
      ELIMINATE: "PREFER",
      DEVELOP: "ACCEPT",
    },
    motives: {
      OPPORTUNISM: "REQUIRE",
      LEVERAGE: "PREFER",
      EFFICIENCY: "PREFER",
      POSITION: "PREFER",
      DENIAL: "PREFER",
      PUNISHMENT: "ACCEPT",
      DOMINANCE: "PREFER",
      ELIMINATION: "ACCEPT",
      PRESERVATION: "DISLIKE",
    },
    resourceAttitudes: {
      POPULATION: "TRADE",
      FFY: "SPEND",
      TERRITORY: "BURN",
      INFRASTRUCTURE: "TRADE",
      ARMOR: "TRADE",
      NAVAL_ASSETS: "TRADE",
      STRATEGIC_WEAPON_CHARGES: "TRADE",
      ALLY_POSITION: "TRADE",
    },
    conditionalRules: [
      "ASKELADD_ATTACK_WEAKNESS_NOT_FAIRNESS",
      "ASKELADD_POSITIONAL_SACRIFICE_FOR_LEVERAGE",
    ],
    customHooks: ["ASKELADD_OPPONENT_MANIPULATION"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: [
      "ASKELADD_EXPLOIT_DISTRACTED_OPPONENTS",
      "ASKELADD_INFRASTRUCTURE_PREDATION_GOALS",
    ],
  },
  arbiter: {
    kind: "STRATEGIC_PORTFOLIO",
    maxPrimary: 2,
    maxSecondary: 3,
    maxBackground: 2,
    defaultResourcePosture: "BALANCED",
    customRules: ["ASKELADD_ASYMMETRIC_VALUE_PRIORITY"],
    customHooks: ["ASKELADD_MANIPULATIVE_PORTFOLIO"],
  },
  persistence: {
    kind: "STRATEGIC",
    temperament: "FLEXIBLE",
    rules: ["ASKELADD_ABANDON_FAIR_FIGHT", "ASKELADD_PERSIST_WHILE_LEVERAGE_GROWS"],
    hooks: [],
  },
  expression: {
    defaultLeeway: "WIDE",
    rules: [
      { trait: "DECEPTIVE", preference: "SIGNATURE" },
      { trait: "RAIDING", preference: "SIGNATURE" },
      { trait: "PICK_WEAK_TARGET", preference: "STRONGLY_LIKE" },
      { trait: "INDIRECT", preference: "STRONGLY_LIKE" },
      { trait: "SACRIFICIAL", preference: "LIKE" },
      { trait: "ENCIRCLEMENT", preference: "LIKE" },
      { trait: "INFORMATION_DENIAL", preference: "LIKE" },
    ],
    hooks: ["ASKELADD_DECEPTION_EXPRESSION"],
  },
  originAdaptation: {
    themes: {
      RAIDING: "REQUIRE",
      INFORMATION: "PREFER",
      ECONOMIC_COMPOUNDING: "PREFER",
      SACRIFICE: "PREFER",
      POSITIONAL_CONTROL: "PREFER",
      DECISIVE_FORCE: "PREFER",
      TRADE: "PREFER",
    },
    affordances: {
      RAID_INFRASTRUCTURE: "REQUIRE",
      LURE_OVEREXTENSION: "PREFER",
      CUT_CONNECTIVITY: "PREFER",
      FORCE_ENEMY_RESPONSE: "PREFER",
      GAIN_INFORMATION_ADVANTAGE: "PREFER",
      SCALE_ECONOMY: "PREFER",
    },
    cautions: {
      OVEREXTENSION_RISK: "RESPECT",
      EXPENSIVE_FAILURE: "TOLERATE",
      SELF_GEOMETRY_RISK: "TOLERATE",
      REQUIRES_GIVING_GROUND: "TOLERATE",
      HIGH_UPFRONT_COST: "RESPECT",
    },
    hooks: {
      signalInterpretation: ["ASKELADD_ORIGIN_WEAKNESS_INTERPRETATION"],
      goalGeneration: ["ASKELADD_ORIGIN_PREDATION_GOALS"],
      planRanking: ["ASKELADD_ORIGIN_ASYMMETRIC_PLAN_RANKING"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "HIGH" },
      { axis: "RETALIATION", expectation: "NORMAL" },
      { axis: "POPULATION_PRESERVATION", expectation: "LOW" },
      { axis: "TERRITORIAL_RISK", expectation: "HIGH" },
      { axis: "WITHDRAWAL", expectation: "HIGH" },
      { axis: "SACRIFICE", expectation: "VERY_HIGH" },
      { axis: "PLAN_PERSISTENCE", expectation: "NORMAL" },
      { axis: "OPPORTUNISM", expectation: "VERY_HIGH" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "HIGH" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "HIGH" },
      { axis: "ALLY_SUPPORT", expectation: "NORMAL" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "VERY_HIGH" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "VERY_LOW" },
      { axis: "NAVAL_USAGE", expectation: "NORMAL" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "NORMAL" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "VERY_HIGH" },
    ],
    customChecks: [
      "ASKELADD_PREFERS_ASYMMETRY_OVER_FAIR_CONTEST",
      "ASKELADD_SACRIFICES_POSITION_FOR_LEVERAGE",
    ],
  },
} as const;

const REINHARD_VON_LOHENGRAMM = {
  id: "REINHARD_VON_LOHENGRAMM",
  evaluators: {
    territory: "STRATEGIC_GEOMETRY",
    economy: "STRATEGIC",
    opponent: "ADAPTIVE",
    forecast: "SCENARIO",
    threat: "STRATEGIC_PREDICTIVE",
    opportunity: "STRATEGIC",
  },
  planners: {
    expansion: "STRATEGIC",
    landWar: "MULTI_FRONT_STRATEGIC",
    defense: "PREDICTIVE",
    counterResponse: "STRATEGIC",
    retreat: "STRATEGIC_SACRIFICE",
    spending: "OPPORTUNITY_COST",
    infrastructure: "STRATEGIC_OPTIMIZER",
    upgrade: "STRATEGIC_TIMING",
    armor: "STRATEGIC",
    naval: "STRATEGIC",
    amphibious: "STRATEGIC",
    strategicWeapons: "STRATEGIC",
    observation: "STRATEGIC_INFORMATION",
    team: "STRATEGIC",
    spawn: "STRATEGIC",
    spawnReconsider: "ADVERSARIAL",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      EXPAND: "PREFER",
      SECURE: "PREFER",
      PRESSURE: "PREFER",
      BREAKTHROUGH: "REQUIRE",
      WEAKEN: "PREFER",
      ELIMINATE: "PREFER",
      CONTROL: "PREFER",
      DENY: "PREFER",
      DEVELOP: "PREFER",
    },
    motives: {
      DOMINANCE: "REQUIRE",
      POSITION: "PREFER",
      LEVERAGE: "PREFER",
      GROWTH: "PREFER",
      EFFICIENCY: "PREFER",
      PREPARATION: "PREFER",
      ELIMINATION: "PREFER",
      OPPORTUNISM: "PREFER",
    },
    resourceAttitudes: {
      POPULATION: "TRADE",
      FFY: "SPEND",
      TERRITORY: "SPEND",
      INFRASTRUCTURE: "SPEND",
      ARMOR: "TRADE",
      NAVAL_ASSETS: "TRADE",
      STRATEGIC_WEAPON_CHARGES: "TRADE",
      ALLY_POSITION: "TRADE",
    },
    conditionalRules: [
      "REINHARD_SEEK_DECISIVE_SUPERIORITY",
      "REINHARD_GLOBAL_POSITION_OVER_LOCAL_GAIN",
    ],
    customHooks: ["REINHARD_GLOBAL_CAMPAIGN_MODEL"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: ["REINHARD_MULTI_THEATER_CAMPAIGN_GOALS", "REINHARD_FORCING_MOVE_GOALS"],
  },
  arbiter: {
    kind: "STRATEGIC_PORTFOLIO",
    maxPrimary: 3,
    maxSecondary: 4,
    maxBackground: 3,
    defaultResourcePosture: "COMMIT",
    customRules: ["REINHARD_GLOBAL_SUPREMACY_PORTFOLIO"],
    customHooks: ["REINHARD_CROSS_DOMAIN_COORDINATION"],
  },
  persistence: {
    kind: "STRATEGIC",
    temperament: "STEADY",
    rules: [
      "REINHARD_PERSIST_ON_STRATEGIC_OBJECTIVE",
      "REINHARD_ABANDON_LOCAL_PLAN_FOR_GLOBAL_ADVANTAGE",
    ],
    hooks: [],
  },
  expression: {
    defaultLeeway: "MODERATE",
    rules: [
      { trait: "CONCENTRATED", preference: "STRONGLY_LIKE" },
      { trait: "MULTI_FRONT", preference: "STRONGLY_LIKE" },
      { trait: "ENCIRCLEMENT", preference: "LIKE" },
      { trait: "OVERWHELMING", preference: "LIKE" },
      { trait: "NETWORK_DENSE", preference: "LIKE" },
      { trait: "HIGH_ROI", preference: "LIKE" },
      { trait: "ARMOR_BREAKTHROUGH", preference: "LIKE" },
      { trait: "SEA_CONTROL", preference: "LIKE" },
      { trait: "COUNTERFORCE", preference: "LIKE" },
    ],
    hooks: ["REINHARD_DECISIVE_CAMPAIGN_EXPRESSION"],
  },
  originAdaptation: {
    themes: {
      DECISIVE_FORCE: "REQUIRE",
      POSITIONAL_CONTROL: "REQUIRE",
      EXPANSION: "PREFER",
      ECONOMIC_COMPOUNDING: "PREFER",
      INDUSTRIALIZATION: "PREFER",
      NAVAL_PROJECTION: "PREFER",
      DISTRIBUTED_PLAY: "PREFER",
      SIEGE: "PREFER",
    },
    affordances: {
      CREATE_BREAKTHROUGH: "REQUIRE",
      MULTI_THEATER_ACCESS: "PREFER",
      FORCE_ENEMY_RESPONSE: "PREFER",
      CUT_CONNECTIVITY: "PREFER",
      SCALE_ECONOMY: "PREFER",
      SCALE_INDUSTRY: "PREFER",
      PROJECT_FROM_SEA: "PREFER",
    },
    cautions: {
      OVEREXTENSION_RISK: "RESPECT",
      SPLIT_FRONT_RISK: "RESPECT",
      EXPENSIVE_FAILURE: "RESPECT",
      HIGH_UPFRONT_COST: "TOLERATE",
      ISOLATED_CORE_RISK: "RESPECT",
    },
    hooks: {
      signalInterpretation: ["REINHARD_ORIGIN_GLOBAL_POSITION_INTERPRETATION"],
      goalGeneration: ["REINHARD_ORIGIN_SUPREMACY_GOALS"],
      arbitration: ["REINHARD_ORIGIN_GLOBAL_PORTFOLIO"],
      planRanking: ["REINHARD_ORIGIN_DECISIVE_USE"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "HIGH" },
      { axis: "RETALIATION", expectation: "HIGH" },
      { axis: "POPULATION_PRESERVATION", expectation: "NORMAL" },
      { axis: "TERRITORIAL_RISK", expectation: "HIGH" },
      { axis: "WITHDRAWAL", expectation: "NORMAL" },
      { axis: "SACRIFICE", expectation: "HIGH" },
      { axis: "PLAN_PERSISTENCE", expectation: "HIGH" },
      { axis: "OPPORTUNISM", expectation: "HIGH" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "HIGH" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "HIGH" },
      { axis: "ALLY_SUPPORT", expectation: "HIGH" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "NORMAL" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "HIGH" },
      { axis: "NAVAL_USAGE", expectation: "HIGH" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "HIGH" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "HIGH" },
    ],
    customChecks: [
      "REINHARD_GLOBAL_OBJECTIVE_BEATS_LOCAL_OPTIMUM",
      "REINHARD_COORDINATES_MULTIPLE_THEATERS",
    ],
  },
} as const;

const YANG_WEN_LI = {
  id: "YANG_WEN_LI",
  evaluators: {
    territory: "STRATEGIC_GEOMETRY",
    economy: "STRATEGIC",
    opponent: "ADAPTIVE",
    forecast: "SCENARIO",
    threat: "STRATEGIC_PREDICTIVE",
    opportunity: "STRATEGIC",
  },
  planners: {
    expansion: "STRATEGIC",
    landWar: "MULTI_FRONT_STRATEGIC",
    defense: "PREDICTIVE",
    counterResponse: "STRATEGIC",
    retreat: "STRATEGIC_SACRIFICE",
    spending: "OPPORTUNITY_COST",
    infrastructure: "STRATEGIC_OPTIMIZER",
    upgrade: "STRATEGIC_TIMING",
    armor: "STRATEGIC",
    naval: "STRATEGIC",
    amphibious: "STRATEGIC",
    strategicWeapons: "STRATEGIC",
    observation: "STRATEGIC_INFORMATION",
    team: "STRATEGIC",
    spawn: "STRATEGIC",
    spawnReconsider: "ADVERSARIAL",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      SURVIVE: "REQUIRE",
      STABILIZE: "PREFER",
      DEFEND: "REQUIRE",
      WITHDRAW: "PREFER",
      SACRIFICE: "ACCEPT",
      COUNTER: "PREFER",
      REPEL: "REQUIRE",
      RETALIATE: "PREFER",
      PRESSURE: "DISLIKE",
      RAID: "DISLIKE",
      ELIMINATE: "DISLIKE",
    },
    motives: {
      SURVIVAL: "PREFER",
      PRESERVATION: "REQUIRE",
      SECURITY: "PREFER",
      STABILITY: "PREFER",
      EFFICIENCY: "PREFER",
      PREPARATION: "PREFER",
      OPPORTUNISM: "PREFER",
      DOMINANCE: "DISLIKE",
      ELIMINATION: "DISLIKE",
      ALLY_SUPPORT: "PREFER",
    },
    resourceAttitudes: {
      POPULATION: "PROTECT",
      FFY: "CONSERVE",
      TERRITORY: "TRADE",
      INFRASTRUCTURE: "CONSERVE",
      ARMOR: "CONSERVE",
      NAVAL_ASSETS: "CONSERVE",
      STRATEGIC_WEAPON_CHARGES: "CONSERVE",
      ALLY_POSITION: "PROTECT",
    },
    conditionalRules: ["YANG_AVOID_UNNECESSARY_HOSTILITY", "YANG_INVITE_OVEREXTENSION_WHEN_SAFE"],
    customHooks: ["YANG_OPPONENT_OVEREXTENSION_MODEL"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: ["YANG_COUNTEROFFENSIVE_AFTER_OVEREXTENSION", "YANG_OPTION_PRESERVING_DEFENSE_GOALS"],
  },
  arbiter: {
    kind: "STRATEGIC_PORTFOLIO",
    maxPrimary: 2,
    maxSecondary: 4,
    maxBackground: 3,
    defaultResourcePosture: "CAUTIOUS",
    customRules: ["YANG_MINIMUM_NECESSARY_WAR", "YANG_PRESERVE_FUTURE_OPTIONS"],
    customHooks: [],
  },
  persistence: {
    kind: "STRATEGIC",
    temperament: "FLEXIBLE",
    rules: [
      "YANG_ABANDON_LOCAL_POSITION_FOR_BETTER_GEOMETRY",
      "YANG_PERSIST_ONLY_WHILE_STRATEGIC_CASE_HOLDS",
    ],
    hooks: [],
  },
  expression: {
    defaultLeeway: "MODERATE",
    rules: [
      { trait: "PATIENT", preference: "SIGNATURE" },
      { trait: "LOW_CASUALTY", preference: "STRONGLY_LIKE" },
      { trait: "INDIRECT", preference: "STRONGLY_LIKE" },
      { trait: "DECEPTIVE", preference: "LIKE" },
      { trait: "ENCIRCLEMENT", preference: "LIKE" },
      { trait: "NATURAL_BARRIER", preference: "LIKE" },
      { trait: "LOW_EXPOSURE", preference: "STRONGLY_LIKE" },
      { trait: "THREAT_FOCUSED", preference: "LIKE" },
    ],
    hooks: ["YANG_OPTION_PRESERVING_EXPRESSION"],
  },
  originAdaptation: {
    themes: {
      FORCE_PRESERVATION: "REQUIRE",
      FORTIFICATION: "PREFER",
      INFORMATION: "PREFER",
      ECONOMIC_COMPOUNDING: "PREFER",
      POSITIONAL_CONTROL: "PREFER",
      SACRIFICE: "ACCEPT",
      DECISIVE_FORCE: "DISLIKE",
      ESCALATION: "DISLIKE",
    },
    affordances: {
      LURE_OVEREXTENSION: "REQUIRE",
      TRADE_GROUND_FOR_CASUALTIES: "PREFER",
      PRESERVE_FORCE: "REQUIRE",
      RETALIATE_EFFICIENTLY: "PREFER",
      HOLD_GROUND: "PREFER",
      GAIN_INFORMATION_ADVANTAGE: "PREFER",
      FORCE_ENEMY_RESPONSE: "DISLIKE",
    },
    cautions: {
      OVEREXTENSION_RISK: "AVOID",
      EXPENSIVE_FAILURE: "AVOID",
      SPLIT_FRONT_RISK: "AVOID",
      ISOLATED_CORE_RISK: "AVOID",
      REQUIRES_GIVING_GROUND: "TOLERATE",
    },
    hooks: {
      signalInterpretation: ["YANG_ORIGIN_DEFENSIVE_GEOMETRY_INTERPRETATION"],
      goalGeneration: ["YANG_ORIGIN_COUNTEROFFENSIVE_GOALS"],
      arbitration: ["YANG_ORIGIN_OPTION_VALUE"],
      planRanking: ["YANG_ORIGIN_MINIMUM_COST_SOLUTION"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "VERY_LOW" },
      { axis: "RETALIATION", expectation: "HIGH" },
      { axis: "POPULATION_PRESERVATION", expectation: "VERY_HIGH" },
      { axis: "TERRITORIAL_RISK", expectation: "LOW" },
      { axis: "WITHDRAWAL", expectation: "VERY_HIGH" },
      { axis: "SACRIFICE", expectation: "HIGH" },
      { axis: "PLAN_PERSISTENCE", expectation: "NORMAL" },
      { axis: "OPPORTUNISM", expectation: "HIGH" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "HIGH" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "HIGH" },
      { axis: "ALLY_SUPPORT", expectation: "HIGH" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "NORMAL" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "VERY_LOW" },
      { axis: "NAVAL_USAGE", expectation: "NORMAL" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "LOW" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "VERY_HIGH" },
    ],
    customChecks: [
      "YANG_AVOIDS_WAR_WITHOUT_STRATEGIC_NEED",
      "YANG_PUNISHES_OVEREXTENSION",
      "YANG_RETREATS_BEFORE_BAD_GEOMETRY_BECOMES_TRAP",
    ],
  },
} as const;

const FRIEREN = {
  id: "FRIEREN",
  evaluators: {
    territory: "STRATEGIC_GEOMETRY",
    economy: "STRATEGIC",
    opponent: "BEHAVIOR_HISTORY",
    forecast: "SCENARIO",
    threat: "OPERATIONAL",
    opportunity: "STRATEGIC",
  },
  planners: {
    expansion: "STRATEGIC",
    landWar: "OPERATIONAL",
    defense: "VALUE_AWARE",
    counterResponse: "EXCHANGE_AWARE",
    retreat: "DEFENSIBLE",
    spending: "OPPORTUNITY_COST",
    infrastructure: "STRATEGIC_OPTIMIZER",
    upgrade: "STRATEGIC_TIMING",
    armor: "STRATEGIC",
    naval: "SEA_CONTROL",
    amphibious: "OPPORTUNITY",
    strategicWeapons: "STRATEGIC",
    observation: "STRATEGIC_INFORMATION",
    team: "OBJECTIVE",
    spawn: "STRATEGIC",
    spawnReconsider: "THREAT_AWARE",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      DEVELOP: "REQUIRE",
      PREPARE: "PREFER",
      SECURE: "PREFER",
      STABILIZE: "PREFER",
      STRIKE: "PREFER",
      BREAKTHROUGH: "PREFER",
      PRESSURE: "DISLIKE",
    },
    motives: {
      PREPARATION: "REQUIRE",
      GROWTH: "PREFER",
      PROSPERITY: "PREFER",
      EFFICIENCY: "PREFER",
      INFORMATION: "PREFER",
      PRESERVATION: "PREFER",
      CURIOSITY: "PREFER",
      DOMINANCE: "DISLIKE",
      SPECTACLE: "DISLIKE",
    },
    resourceAttitudes: {
      POPULATION: "CONSERVE",
      FFY: "CONSERVE",
      TERRITORY: "CONSERVE",
      INFRASTRUCTURE: "SPEND",
      ARMOR: "CONSERVE",
      NAVAL_ASSETS: "CONSERVE",
      STRATEGIC_WEAPON_CHARGES: "CONSERVE",
      ALLY_POSITION: "CONSERVE",
    },
    conditionalRules: ["FRIEREN_DELAY_MARGINAL_COMMITMENT", "FRIEREN_COMMIT_WHEN_ADVANTAGE_MATURES"],
    customHooks: ["FRIEREN_LONG_HORIZON_ACCUMULATION"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: ["FRIEREN_PREPARATION_CHAIN_GOALS", "FRIEREN_MATURE_ADVANTAGE_STRIKE_GOALS"],
  },
  arbiter: {
    kind: "STRATEGIC_PORTFOLIO",
    maxPrimary: 2,
    maxSecondary: 3,
    maxBackground: 3,
    defaultResourcePosture: "CAUTIOUS",
    customRules: ["FRIEREN_LOW_URGENCY_LONG_HORIZON_PRIORITY"],
    customHooks: [],
  },
  persistence: {
    kind: "STRATEGIC",
    temperament: "STEADY",
    rules: ["FRIEREN_TOLERATE_SLOW_PROGRESS", "FRIEREN_DECISIVE_AFTER_PREPARATION_THRESHOLD"],
    hooks: [],
  },
  expression: {
    defaultLeeway: "WIDE",
    rules: [
      { trait: "PATIENT", preference: "SIGNATURE" },
      { trait: "LONG_HORIZON", preference: "SIGNATURE" },
      { trait: "DEVELOPMENT_HEAVY", preference: "STRONGLY_LIKE" },
      { trait: "HIGH_ROI", preference: "LIKE" },
      { trait: "LOW_CASUALTY", preference: "LIKE" },
      { trait: "PRECISION_STRIKE", preference: "LIKE" },
    ],
    hooks: ["FRIEREN_PATIENT_SOLUTION_SELECTION"],
  },
  originAdaptation: {
    themes: {
      ECONOMIC_COMPOUNDING: "REQUIRE",
      INFRASTRUCTURE: "PREFER",
      GROWTH: "PREFER",
      SPECIALIZATION: "PREFER",
      SIEGE: "PREFER",
      DECISIVE_FORCE: "PREFER",
      INFORMATION: "PREFER",
      ESCALATION: "DISLIKE",
    },
    affordances: {
      BUILD_HIGH_LEVEL_INFRASTRUCTURE: "PREFER",
      SCALE_ECONOMY: "PREFER",
      SCALE_GROWTH: "PREFER",
      FIGHT_FROM_RANGE: "PREFER",
      SIEGE_STATIC_POSITIONS: "PREFER",
      GAIN_INFORMATION_ADVANTAGE: "PREFER",
      CREATE_BREAKTHROUGH: "ACCEPT",
    },
    cautions: {
      LONG_PAYBACK: "TOLERATE",
      SETUP_TIME: "TOLERATE",
      HIGH_UPFRONT_COST: "RESPECT",
      HIGH_LIQUIDITY_NEED: "RESPECT",
      OVEREXTENSION_RISK: "AVOID",
      EXPENSIVE_FAILURE: "AVOID",
    },
    hooks: {
      signalInterpretation: ["FRIEREN_ORIGIN_LONG_HORIZON_INTERPRETATION"],
      arbitration: ["FRIEREN_ORIGIN_DELAY_FOR_COMPOUNDING"],
      planRanking: ["FRIEREN_ORIGIN_MATURE_ADVANTAGE_USE"],
      persistence: ["FRIEREN_ORIGIN_PATIENCE"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "LOW" },
      { axis: "RETALIATION", expectation: "NORMAL" },
      { axis: "POPULATION_PRESERVATION", expectation: "HIGH" },
      { axis: "TERRITORIAL_RISK", expectation: "LOW" },
      { axis: "WITHDRAWAL", expectation: "NORMAL" },
      { axis: "SACRIFICE", expectation: "LOW" },
      { axis: "PLAN_PERSISTENCE", expectation: "VERY_HIGH" },
      { axis: "OPPORTUNISM", expectation: "NORMAL" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "VERY_HIGH" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "HIGH" },
      { axis: "ALLY_SUPPORT", expectation: "NORMAL" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "NORMAL" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "LOW" },
      { axis: "NAVAL_USAGE", expectation: "LOW" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "HIGH" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "VERY_HIGH" },
    ],
    customChecks: [
      "FRIEREN_PREFERS_FUTURE_ADVANTAGE_OVER_MARGINAL_IMMEDIACY",
      "FRIEREN_COMMITS_DECISIVELY_AFTER_PREPARATION",
    ],
  },
} as const;

const UBEL = {
  id: "UBEL",
  evaluators: {
    territory: "STRATEGIC_GEOMETRY",
    economy: "RETURN_AWARE",
    opponent: "ADAPTIVE",
    forecast: "SCENARIO",
    threat: "OPERATIONAL",
    opportunity: "STRATEGIC",
  },
  planners: {
    expansion: "STRATEGIC",
    landWar: "MULTI_FRONT_STRATEGIC",
    defense: "VALUE_AWARE",
    counterResponse: "EXCHANGE_AWARE",
    retreat: "STRATEGIC_SACRIFICE",
    spending: "OPPORTUNITY_COST",
    infrastructure: "NETWORK_AWARE",
    upgrade: "VALUE",
    armor: "STRATEGIC",
    naval: "SEA_CONTROL",
    amphibious: "STRATEGIC",
    strategicWeapons: "STRATEGIC",
    observation: "THREAT_FOCUSED",
    team: "OBJECTIVE",
    spawn: "STRATEGIC",
    spawnReconsider: "ADVERSARIAL",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      PRESSURE: "PREFER",
      RAID: "PREFER",
      BREAKTHROUGH: "REQUIRE",
      WEAKEN: "PREFER",
      ELIMINATE: "PREFER",
      SACRIFICE: "PREFER",
      STRIKE: "PREFER",
    },
    motives: {
      OPPORTUNISM: "REQUIRE",
      CURIOSITY: "PREFER",
      LEVERAGE: "PREFER",
      DOMINANCE: "PREFER",
      SPECTACLE: "ACCEPT",
      PRESERVATION: "DISLIKE",
      EFFICIENCY: "ACCEPT",
    },
    resourceAttitudes: {
      POPULATION: "TRADE",
      FFY: "SPEND",
      TERRITORY: "TRADE",
      INFRASTRUCTURE: "TRADE",
      ARMOR: "SPEND",
      NAVAL_ASSETS: "TRADE",
      STRATEGIC_WEAPON_CHARGES: "SPEND",
      ALLY_POSITION: "TRADE",
    },
    conditionalRules: ["UBEL_ALLOW_HIGH_UPSIDE_NONSTANDARD_LINES", "UBEL_PRESS_VISIBLE_BREAKTHROUGH_WINDOWS"],
    customHooks: ["UBEL_INTUITIVE_OPPORTUNITY_INTERPRETATION"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: ["UBEL_STRANGE_LINE_GOALS", "UBEL_HIGH_UPSIDE_BREAKTHROUGH_GOALS"],
  },
  arbiter: {
    kind: "STRATEGIC_PORTFOLIO",
    maxPrimary: 2,
    maxSecondary: 3,
    maxBackground: 2,
    defaultResourcePosture: "COMMIT",
    customRules: ["UBEL_HIGH_UPSIDE_TOLERANCE"],
    customHooks: [],
  },
  persistence: {
    kind: "STRATEGIC",
    temperament: "FLEXIBLE",
    rules: ["UBEL_STAY_WITH_PROMISING_ODD_LINE", "UBEL_DROP_LINE_WHEN_OPENING_VANISHES"],
    hooks: [],
  },
  expression: {
    defaultLeeway: "SIGNATURE",
    rules: [
      { trait: "DECEPTIVE", preference: "STRONGLY_LIKE" },
      { trait: "HIGH_TEMPO", preference: "STRONGLY_LIKE" },
      { trait: "SACRIFICIAL", preference: "LIKE" },
      { trait: "CHALLENGE_STRONG_TARGET", preference: "LIKE" },
      { trait: "SURPRISE_LANDING", preference: "STRONGLY_LIKE" },
      { trait: "DEEP_STRIKE", preference: "LIKE" },
      { trait: "TOPOLOGY_STRIKE", preference: "LIKE" },
    ],
    hooks: ["UBEL_UNCONVENTIONAL_SOLUTION_EXPRESSION"],
  },
  originAdaptation: {
    themes: {
      DECISIVE_FORCE: "REQUIRE",
      RAIDING: "PREFER",
      TERRITORIAL_SHAPING: "PREFER",
      ESCALATION: "PREFER",
      SACRIFICE: "PREFER",
      SPECIALIZATION: "PREFER",
      INFORMATION: "ACCEPT",
    },
    affordances: {
      CREATE_BREAKTHROUGH: "REQUIRE",
      RAID_INFRASTRUCTURE: "PREFER",
      SHAPE_TERRITORY: "PREFER",
      CUT_CONNECTIVITY: "PREFER",
      FORCE_ENEMY_RESPONSE: "PREFER",
      ERODE_TERRITORY_AT_RANGE: "PREFER",
    },
    cautions: {
      OVEREXTENSION_RISK: "TOLERATE",
      EXPENSIVE_FAILURE: "TOLERATE",
      SELF_GEOMETRY_RISK: "TOLERATE",
      CLOSE_RANGE_VULNERABILITY: "RESPECT",
      COUNTERATTACK_WINDOW: "TOLERATE",
    },
    hooks: {
      signalInterpretation: ["UBEL_ORIGIN_HIGH_UPSIDE_INTERPRETATION"],
      goalGeneration: ["UBEL_ORIGIN_UNCONVENTIONAL_GOALS"],
      planRanking: ["UBEL_ORIGIN_RISK_TOLERANT_RANKING"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "HIGH" },
      { axis: "RETALIATION", expectation: "NORMAL" },
      { axis: "POPULATION_PRESERVATION", expectation: "LOW" },
      { axis: "TERRITORIAL_RISK", expectation: "VERY_HIGH" },
      { axis: "WITHDRAWAL", expectation: "NORMAL" },
      { axis: "SACRIFICE", expectation: "HIGH" },
      { axis: "PLAN_PERSISTENCE", expectation: "NORMAL" },
      { axis: "OPPORTUNISM", expectation: "VERY_HIGH" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "LOW" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "NORMAL" },
      { axis: "ALLY_SUPPORT", expectation: "LOW" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "NORMAL" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "HIGH" },
      { axis: "NAVAL_USAGE", expectation: "NORMAL" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "HIGH" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "VERY_HIGH" },
    ],
    customChecks: [
      "UBEL_TAKES_HIGH_UPSIDE_LINES_OTHER_D4S_REJECT",
      "UBEL_REMAINS_LEGALLY_COHERENT_NOT_RANDOM",
    ],
  },
} as const;

const TANYA_DEGURECHAFF = {
  id: "TANYA_DEGURECHAFF",
  evaluators: {
    territory: "STRATEGIC_GEOMETRY",
    economy: "STRATEGIC",
    opponent: "ADAPTIVE",
    forecast: "SCENARIO",
    threat: "STRATEGIC_PREDICTIVE",
    opportunity: "STRATEGIC",
  },
  planners: {
    expansion: "STRATEGIC",
    landWar: "MULTI_FRONT_STRATEGIC",
    defense: "PREDICTIVE",
    counterResponse: "STRATEGIC",
    retreat: "STRATEGIC_SACRIFICE",
    spending: "OPPORTUNITY_COST",
    infrastructure: "STRATEGIC_OPTIMIZER",
    upgrade: "STRATEGIC_TIMING",
    armor: "STRATEGIC",
    naval: "SEA_CONTROL",
    amphibious: "STRATEGIC",
    strategicWeapons: "STRATEGIC",
    observation: "STRATEGIC_INFORMATION",
    team: "OBJECTIVE",
    spawn: "STRATEGIC",
    spawnReconsider: "ADVERSARIAL",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      PREPARE: "PREFER",
      PRESSURE: "PREFER",
      BREAKTHROUGH: "REQUIRE",
      COUNTER: "PREFER",
      REPEL: "PREFER",
      STRIKE: "PREFER",
      WEAKEN: "PREFER",
      SACRIFICE: "ACCEPT",
    },
    motives: {
      EFFICIENCY: "REQUIRE",
      PREPARATION: "PREFER",
      LEVERAGE: "PREFER",
      POSITION: "PREFER",
      DENIAL: "PREFER",
      DOMINANCE: "ACCEPT",
      SPECTACLE: "FORBID",
      PRESERVATION: "ACCEPT",
    },
    resourceAttitudes: {
      POPULATION: "TRADE",
      FFY: "SPEND",
      TERRITORY: "TRADE",
      INFRASTRUCTURE: "CONSERVE",
      ARMOR: "CONSERVE",
      NAVAL_ASSETS: "CONSERVE",
      STRATEGIC_WEAPON_CHARGES: "TRADE",
      ALLY_POSITION: "TRADE",
    },
    conditionalRules: ["TANYA_CONCENTRATE_FORCE_FOR_EXPECTED_VALUE", "TANYA_REJECT_WASTE_WITHOUT_RETURN"],
    customHooks: ["TANYA_QUANTITATIVE_WAR_MODEL"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: ["TANYA_BREAKTHROUGH_PREPARATION_GOALS", "TANYA_STRATEGIC_WEAPON_EFFICIENCY_GOALS"],
  },
  arbiter: {
    kind: "STRATEGIC_PORTFOLIO",
    maxPrimary: 2,
    maxSecondary: 3,
    maxBackground: 2,
    defaultResourcePosture: "COMMIT",
    customRules: ["TANYA_EXPECTED_VALUE_PORTFOLIO"],
    customHooks: [],
  },
  persistence: {
    kind: "STRATEGIC",
    temperament: "STEADY",
    rules: ["TANYA_PERSIST_WHILE_EXPECTED_VALUE_POSITIVE", "TANYA_CANCEL_SUNK_COST_OPERATION"],
    hooks: [],
  },
  expression: {
    defaultLeeway: "NARROW",
    rules: [
      { trait: "CONCENTRATED", preference: "SIGNATURE" },
      { trait: "HIGH_TEMPO", preference: "LIKE" },
      { trait: "OVERWHELMING", preference: "LIKE" },
      { trait: "MILITARY_FIRST", preference: "STRONGLY_LIKE" },
      { trait: "ARMOR_BREAKTHROUGH", preference: "STRONGLY_LIKE" },
      { trait: "PRECISION_STRIKE", preference: "LIKE" },
      { trait: "COUNTERFORCE", preference: "LIKE" },
    ],
    hooks: ["TANYA_EFFICIENT_FORCE_EXPRESSION"],
  },
  originAdaptation: {
    themes: {
      DECISIVE_FORCE: "REQUIRE",
      SIEGE: "PREFER",
      DETERRENCE: "PREFER",
      ECONOMIC_COMPOUNDING: "PREFER",
      SPECIALIZATION: "PREFER",
      ESCALATION: "ACCEPT",
      FORCE_PRESERVATION: "ACCEPT",
    },
    affordances: {
      CREATE_BREAKTHROUGH: "REQUIRE",
      FIGHT_FROM_RANGE: "PREFER",
      SIEGE_STATIC_POSITIONS: "PREFER",
      FORCE_ENEMY_RESPONSE: "PREFER",
      REDUCE_INTERCEPTION_WINDOW: "PREFER",
      SCALE_ECONOMY: "PREFER",
    },
    cautions: {
      EXPENSIVE_FAILURE: "AVOID",
      HIGH_UPFRONT_COST: "RESPECT",
      LOW_MOBILITY: "RESPECT",
      LONG_RELOAD: "RESPECT",
      OVEREXTENSION_RISK: "AVOID",
      COUNTERATTACK_WINDOW: "RESPECT",
    },
    hooks: {
      signalInterpretation: ["TANYA_ORIGIN_EXPECTED_VALUE_INTERPRETATION"],
      goalGeneration: ["TANYA_ORIGIN_FORCE_CONCENTRATION_GOALS"],
      arbitration: ["TANYA_ORIGIN_OPPORTUNITY_COST"],
      planRanking: ["TANYA_ORIGIN_MILITARY_EFFICIENCY"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "HIGH" },
      { axis: "RETALIATION", expectation: "HIGH" },
      { axis: "POPULATION_PRESERVATION", expectation: "NORMAL" },
      { axis: "TERRITORIAL_RISK", expectation: "NORMAL" },
      { axis: "WITHDRAWAL", expectation: "NORMAL" },
      { axis: "SACRIFICE", expectation: "HIGH" },
      { axis: "PLAN_PERSISTENCE", expectation: "HIGH" },
      { axis: "OPPORTUNISM", expectation: "HIGH" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "HIGH" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "VERY_HIGH" },
      { axis: "ALLY_SUPPORT", expectation: "NORMAL" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "HIGH" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "LOW" },
      { axis: "NAVAL_USAGE", expectation: "LOW" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "VERY_HIGH" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "VERY_HIGH" },
    ],
    customChecks: [
      "TANYA_PREFERS_EXPECTED_VALUE_OVER_SPECTACLE",
      "TANYA_CONCENTRATES_FORCE_AND_TIMING",
      "TANYA_DOES_NOT_CONFUSE_RUTHLESSNESS_WITH_WASTE",
    ],
  },
} as const;

const KISS_SHOT_ACEROLA_ORION_HEART_UNDER_BLADE = {
  id: "KISS_SHOT_ACEROLA_ORION_HEART_UNDER_BLADE",
  evaluators: {
    territory: "OPERATIONAL",
    economy: "RETURN_AWARE",
    opponent: "BEHAVIOR_HISTORY",
    forecast: "SHORT_HORIZON",
    threat: "OPERATIONAL",
    opportunity: "OPERATIONAL",
  },
  planners: {
    expansion: "TERRAIN_AWARE",
    landWar: "OPERATIONAL",
    defense: "VALUE_AWARE",
    counterResponse: "EXCHANGE_AWARE",
    retreat: "DEFENSIBLE",
    spending: "PRIORITY",
    infrastructure: "NETWORK_AWARE",
    upgrade: "VALUE",
    armor: "OPERATIONAL",
    naval: "SEA_CONTROL",
    amphibious: "OPPORTUNITY",
    strategicWeapons: "OPERATIONAL",
    observation: "THREAT_FOCUSED",
    team: "OBJECTIVE",
    spawn: "TERRAIN_AWARE",
    spawnReconsider: "THREAT_AWARE",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      SURVIVE: "REQUIRE",
      PRESSURE: "PREFER",
      BREAKTHROUGH: "PREFER",
      ELIMINATE: "PREFER",
      CONTROL: "PREFER",
      STRIKE: "PREFER",
      DEVELOP: "ACCEPT",
    },
    motives: {
      DOMINANCE: "REQUIRE",
      PRESERVATION: "PREFER",
      SPECTACLE: "PREFER",
      LEVERAGE: "PREFER",
      GROWTH: "PREFER",
      OPPORTUNISM: "ACCEPT",
    },
    resourceAttitudes: {
      POPULATION: "TRADE",
      FFY: "SPEND",
      TERRITORY: "SPEND",
      INFRASTRUCTURE: "CONSERVE",
      ARMOR: "CONSERVE",
      NAVAL_ASSETS: "PROTECT",
      STRATEGIC_WEAPON_CHARGES: "SPEND",
      ALLY_POSITION: "TRADE",
    },
    conditionalRules: ["KISSSHOT_PRESS_ADVANTAGE", "KISSSHOT_PROTECT_IRREPLACEABLE_ELITE_ASSET"],
    customHooks: [],
  },
  goalGenerator: { ruleSets: ALL_GOAL_RULE_SETS, customRules: ["KISSSHOT_DOMINANCE_GOALS"] },
  arbiter: {
    kind: "CONTEXTUAL",
    maxPrimary: 2,
    maxSecondary: 2,
    maxBackground: 1,
    defaultResourcePosture: "COMMIT",
    customRules: ["KISSSHOT_OVERWHELMING_COMMITMENT_PRIORITY"],
    customHooks: [],
  },
  persistence: {
    kind: "CONTEXTUAL",
    temperament: "STUBBORN",
    rules: ["KISSSHOT_PRESS_WHILE_DOMINANT", "KISSSHOT_PRESERVE_UNIQUE_POWER_ASSET"],
    hooks: [],
  },
  expression: {
    defaultLeeway: "WIDE",
    rules: [
      { trait: "OVERWHELMING", preference: "SIGNATURE" },
      { trait: "CHALLENGE_STRONG_TARGET", preference: "LIKE" },
      { trait: "FLAGSHIP", preference: "SIGNATURE" },
      { trait: "ARMOR_CONCENTRATION", preference: "LIKE" },
      { trait: "MASS_STRIKE", preference: "LIKE" },
    ],
    hooks: ["KISSSHOT_DOMINANT_EXPRESSION"],
  },
  originAdaptation: {
    themes: {
      DECISIVE_FORCE: "REQUIRE",
      FORCE_PRESERVATION: "PREFER",
      SPECIALIZATION: "PREFER",
      NAVAL_PROJECTION: "PREFER",
      DETERRENCE: "PREFER",
      GROWTH: "PREFER",
      ESCALATION: "PREFER",
    },
    affordances: {
      PRESERVE_FORCE: "PREFER",
      CREATE_BREAKTHROUGH: "PREFER",
      PROJECT_FROM_SEA: "PREFER",
      PROTECT_HIGH_VALUE_ASSET: "REQUIRE",
      FORCE_ENEMY_RESPONSE: "PREFER",
    },
    cautions: {
      EXPENSIVE_FAILURE: "AVOID",
      REQUIRES_VETERANCY: "RESPECT",
      OVEREXTENSION_RISK: "TOLERATE",
      HIGH_UPFRONT_COST: "TOLERATE",
    },
    hooks: {
      arbitration: ["KISSSHOT_ORIGIN_DOMINANT_ASSET_PRIORITY"],
      planRanking: ["KISSSHOT_ORIGIN_OVERWHELMING_USE"],
      persistence: ["KISSSHOT_ORIGIN_ELITE_ASSET_PRESERVATION"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "HIGH" },
      { axis: "RETALIATION", expectation: "HIGH" },
      { axis: "POPULATION_PRESERVATION", expectation: "NORMAL" },
      { axis: "TERRITORIAL_RISK", expectation: "HIGH" },
      { axis: "WITHDRAWAL", expectation: "LOW" },
      { axis: "SACRIFICE", expectation: "NORMAL" },
      { axis: "PLAN_PERSISTENCE", expectation: "HIGH" },
      { axis: "OPPORTUNISM", expectation: "NORMAL" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "NORMAL" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "NORMAL" },
      { axis: "ALLY_SUPPORT", expectation: "LOW" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "LOW" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "HIGH" },
      { axis: "NAVAL_USAGE", expectation: "HIGH" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "HIGH" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "VERY_HIGH" },
    ],
    customChecks: ["KISSSHOT_PREFERS_DOMINANT_COMMITMENT", "KISSSHOT_PROTECTS_SIGNATURE_ELITE_ASSETS"],
  },
} as const;

const HANEKAWA_TSUBASA = {
  id: "HANEKAWA_TSUBASA",
  evaluators: {
    territory: "STRATEGIC_GEOMETRY",
    economy: "STRATEGIC",
    opponent: "ADAPTIVE",
    forecast: "SCENARIO",
    threat: "STRATEGIC_PREDICTIVE",
    opportunity: "STRATEGIC",
  },
  planners: {
    expansion: "STRATEGIC",
    landWar: "OPERATIONAL",
    defense: "PREDICTIVE",
    counterResponse: "STRATEGIC",
    retreat: "STRATEGIC_SACRIFICE",
    spending: "OPPORTUNITY_COST",
    infrastructure: "STRATEGIC_OPTIMIZER",
    upgrade: "STRATEGIC_TIMING",
    armor: "OPERATIONAL",
    naval: "SEA_CONTROL",
    amphibious: "OPPORTUNITY",
    strategicWeapons: "OPERATIONAL",
    observation: "STRATEGIC_INFORMATION",
    team: "STRATEGIC",
    spawn: "STRATEGIC",
    spawnReconsider: "ADVERSARIAL",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      PREPARE: "PREFER",
      DEVELOP: "PREFER",
      SECURE: "PREFER",
      COUNTER: "PREFER",
      DEFEND: "PREFER",
      WEAKEN: "ACCEPT",
      PRESSURE: "DISLIKE",
    },
    motives: {
      INFORMATION: "REQUIRE",
      EFFICIENCY: "REQUIRE",
      PREPARATION: "PREFER",
      STABILITY: "PREFER",
      PRESERVATION: "PREFER",
      OPPORTUNISM: "PREFER",
      DOMINANCE: "DISLIKE",
      SPECTACLE: "DISLIKE",
    },
    resourceAttitudes: {
      POPULATION: "CONSERVE",
      FFY: "SPEND",
      TERRITORY: "CONSERVE",
      INFRASTRUCTURE: "CONSERVE",
      ARMOR: "CONSERVE",
      NAVAL_ASSETS: "CONSERVE",
      STRATEGIC_WEAPON_CHARGES: "CONSERVE",
      ALLY_POSITION: "CONSERVE",
    },
    conditionalRules: ["HANEKAWA_SEEK_INFORMATION_BEFORE_COMMITMENT", "HANEKAWA_UPDATE_MODEL_ON_OBSERVED_BEHAVIOR"],
    customHooks: ["HANEKAWA_ANALYTICAL_STATE_SYNTHESIS"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: ["HANEKAWA_INFORMATION_GAP_GOALS", "HANEKAWA_EVIDENCE_BASED_RESPONSE_GOALS"],
  },
  arbiter: {
    kind: "STRATEGIC_PORTFOLIO",
    maxPrimary: 2,
    maxSecondary: 3,
    maxBackground: 3,
    defaultResourcePosture: "BALANCED",
    customRules: ["HANEKAWA_INFORMATION_VALUE_PORTFOLIO"],
    customHooks: [],
  },
  persistence: {
    kind: "STRATEGIC",
    temperament: "FLEXIBLE",
    rules: ["HANEKAWA_REPLAN_ON_NEW_EVIDENCE"],
    hooks: [],
  },
  expression: {
    defaultLeeway: "NARROW",
    rules: [
      { trait: "EFFICIENT", preference: "SIGNATURE" },
      { trait: "COMPACT", preference: "LIKE" },
      { trait: "NETWORK_DENSE", preference: "LIKE" },
      { trait: "LOW_CASUALTY", preference: "LIKE" },
      { trait: "PATIENT", preference: "LIKE" },
      { trait: "BROAD_COVERAGE", preference: "STRONGLY_LIKE" },
      { trait: "THREAT_FOCUSED", preference: "STRONGLY_LIKE" },
      { trait: "COUNTERINTELLIGENCE", preference: "LIKE" },
    ],
    hooks: ["HANEKAWA_ANALYTICAL_EXPRESSION"],
  },
  originAdaptation: {
    themes: {
      INFORMATION: "REQUIRE",
      ECONOMIC_COMPOUNDING: "PREFER",
      INFRASTRUCTURE: "PREFER",
      FORCE_PRESERVATION: "PREFER",
      SPECIALIZATION: "PREFER",
      POSITIONAL_CONTROL: "PREFER",
    },
    affordances: {
      GAIN_INFORMATION_ADVANTAGE: "REQUIRE",
      PROTECT_HIGH_VALUE_ASSET: "PREFER",
      BUILD_HIGH_LEVEL_INFRASTRUCTURE: "PREFER",
      RETALIATE_EFFICIENTLY: "PREFER",
      SCALE_ECONOMY: "PREFER",
    },
    cautions: {
      EXPENSIVE_FAILURE: "AVOID",
      OVEREXTENSION_RISK: "AVOID",
      HIGH_UPFRONT_COST: "RESPECT",
      HIGH_LIQUIDITY_NEED: "RESPECT",
      SELF_GEOMETRY_RISK: "RESPECT",
      SPLIT_FRONT_RISK: "RESPECT",
    },
    hooks: {
      signalInterpretation: ["HANEKAWA_ORIGIN_INFORMATION_SYNTHESIS"],
      goalGeneration: ["HANEKAWA_ORIGIN_INFORMATION_GOALS"],
      arbitration: ["HANEKAWA_ORIGIN_EVIDENCE_WEIGHTING"],
      planRanking: ["HANEKAWA_ORIGIN_EFFICIENT_USE"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "LOW" },
      { axis: "RETALIATION", expectation: "NORMAL" },
      { axis: "POPULATION_PRESERVATION", expectation: "HIGH" },
      { axis: "TERRITORIAL_RISK", expectation: "LOW" },
      { axis: "WITHDRAWAL", expectation: "HIGH" },
      { axis: "SACRIFICE", expectation: "LOW" },
      { axis: "PLAN_PERSISTENCE", expectation: "NORMAL" },
      { axis: "OPPORTUNISM", expectation: "HIGH" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "HIGH" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "VERY_HIGH" },
      { axis: "ALLY_SUPPORT", expectation: "HIGH" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "NORMAL" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "LOW" },
      { axis: "NAVAL_USAGE", expectation: "NORMAL" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "NORMAL" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "HIGH" },
    ],
    customChecks: [
      "HANEKAWA_CHANGES_PLANS_WHEN_EVIDENCE_CHANGES",
      "HANEKAWA_INFORMATION_GATHERING_PRECEDES_RISKY_COMMITMENT",
    ],
  },
} as const;

const KAIKI_DEISHUU = {
  id: "KAIKI_DEISHUU",
  evaluators: {
    territory: "OPERATIONAL",
    economy: "STRATEGIC",
    opponent: "BEHAVIOR_HISTORY",
    forecast: "SHORT_HORIZON",
    threat: "OPERATIONAL",
    opportunity: "STRATEGIC",
  },
  planners: {
    expansion: "TERRAIN_AWARE",
    landWar: "OPERATIONAL",
    defense: "VALUE_AWARE",
    counterResponse: "EXCHANGE_AWARE",
    retreat: "DEFENSIBLE",
    spending: "OPPORTUNITY_COST",
    infrastructure: "NETWORK_AWARE",
    upgrade: "VALUE",
    armor: "OPERATIONAL",
    naval: "SEA_CONTROL",
    amphibious: "OPPORTUNITY",
    strategicWeapons: "OPERATIONAL",
    observation: "THREAT_FOCUSED",
    team: "BASIC",
    spawn: "TERRAIN_AWARE",
    spawnReconsider: "THREAT_AWARE",
  },
  doctrine: {
    defaultJudgment: "ACCEPT",
    goalKinds: {
      DEVELOP: "PREFER",
      RAID: "PREFER",
      WEAKEN: "PREFER",
      WITHDRAW: "PREFER",
      PRESSURE: "ACCEPT",
      BREAKTHROUGH: "DISLIKE",
      ELIMINATE: "DISLIKE",
      SUPPORT_ALLY: "DISLIKE",
    },
    motives: {
      PROSPERITY: "REQUIRE",
      EFFICIENCY: "PREFER",
      OPPORTUNISM: "REQUIRE",
      LEVERAGE: "PREFER",
      INFORMATION: "PREFER",
      PRESERVATION: "PREFER",
      DOMINANCE: "DISLIKE",
      ELIMINATION: "DISLIKE",
      SPECTACLE: "FORBID",
      ALLY_SUPPORT: "DISLIKE",
    },
    resourceAttitudes: {
      POPULATION: "CONSERVE",
      FFY: "CONSERVE",
      TERRITORY: "TRADE",
      INFRASTRUCTURE: "CONSERVE",
      ARMOR: "CONSERVE",
      NAVAL_ASSETS: "CONSERVE",
      STRATEGIC_WEAPON_CHARGES: "CONSERVE",
      ALLY_POSITION: "TRADE",
    },
    conditionalRules: ["KAIKI_AVOID_FAIR_FIGHTS", "KAIKI_REQUIRE_PROFITABLE_CONFLICT_CASE"],
    customHooks: ["KAIKI_PROFITABILITY_MODEL"],
  },
  goalGenerator: {
    ruleSets: ALL_GOAL_RULE_SETS,
    customRules: ["KAIKI_PROFITABLE_WAR_GOALS", "KAIKI_LOW_COST_EXIT_GOALS"],
  },
  arbiter: {
    kind: "CONTEXTUAL",
    maxPrimary: 1,
    maxSecondary: 3,
    maxBackground: 2,
    defaultResourcePosture: "CAUTIOUS",
    customRules: ["KAIKI_PROFIT_FIRST_ARBITRATION"],
    customHooks: [],
  },
  persistence: {
    kind: "CONTEXTUAL",
    temperament: "FLEXIBLE",
    rules: ["KAIKI_EXIT_WHEN_MARGIN_DISAPPEARS"],
    hooks: [],
  },
  expression: {
    defaultLeeway: "WIDE",
    rules: [
      { trait: "DECEPTIVE", preference: "SIGNATURE" },
      { trait: "PICK_WEAK_TARGET", preference: "SIGNATURE" },
      { trait: "INDIRECT", preference: "STRONGLY_LIKE" },
      { trait: "RAIDING", preference: "STRONGLY_LIKE" },
      { trait: "PATIENT", preference: "LIKE" },
      { trait: "HIGH_ROI", preference: "SIGNATURE" },
      { trait: "LIQUIDITY_HEAVY", preference: "LIKE" },
      { trait: "PIRACY", preference: "LIKE" },
      { trait: "INFORMATION_DENIAL", preference: "LIKE" },
    ],
    hooks: ["KAIKI_PROFITABLE_DECEPTION_EXPRESSION"],
  },
  originAdaptation: {
    themes: {
      ECONOMIC_COMPOUNDING: "REQUIRE",
      TRADE: "PREFER",
      RAIDING: "PREFER",
      INFORMATION: "PREFER",
      FORCE_PRESERVATION: "PREFER",
      SACRIFICE: "ACCEPT",
      DECISIVE_FORCE: "DISLIKE",
    },
    affordances: {
      SCALE_ECONOMY: "REQUIRE",
      SCALE_TRADE: "PREFER",
      RAID_INFRASTRUCTURE: "PREFER",
      PRESERVE_FORCE: "PREFER",
      LURE_OVEREXTENSION: "PREFER",
      GAIN_INFORMATION_ADVANTAGE: "PREFER",
      FORCE_ENEMY_RESPONSE: "DISLIKE",
    },
    cautions: {
      EXPENSIVE_FAILURE: "AVOID",
      HIGH_UPFRONT_COST: "AVOID",
      HIGH_LIQUIDITY_NEED: "RESPECT",
      OVEREXTENSION_RISK: "AVOID",
      SPLIT_FRONT_RISK: "AVOID",
      COUNTERATTACK_WINDOW: "AVOID",
    },
    hooks: {
      signalInterpretation: ["KAIKI_ORIGIN_PROFIT_INTERPRETATION"],
      goalGeneration: ["KAIKI_ORIGIN_PROFITABLE_GOALS"],
      arbitration: ["KAIKI_ORIGIN_MARGIN_ARBITRATION"],
      planRanking: ["KAIKI_ORIGIN_CHEAPEST_PROFITABLE_USE"],
    },
  },
  fidelity: {
    rules: [
      { axis: "HOSTILITY_INITIATION", expectation: "LOW" },
      { axis: "RETALIATION", expectation: "LOW" },
      { axis: "POPULATION_PRESERVATION", expectation: "HIGH" },
      { axis: "TERRITORIAL_RISK", expectation: "VERY_LOW" },
      { axis: "WITHDRAWAL", expectation: "VERY_HIGH" },
      { axis: "SACRIFICE", expectation: "NORMAL" },
      { axis: "PLAN_PERSISTENCE", expectation: "LOW" },
      { axis: "OPPORTUNISM", expectation: "VERY_HIGH" },
      { axis: "ECONOMIC_INVESTMENT", expectation: "VERY_HIGH" },
      { axis: "INFRASTRUCTURE_EFFICIENCY", expectation: "HIGH" },
      { axis: "ALLY_SUPPORT", expectation: "VERY_LOW" },
      { axis: "WEAK_TARGET_PREFERENCE", expectation: "VERY_HIGH" },
      { axis: "STRONG_TARGET_PREFERENCE", expectation: "VERY_LOW" },
      { axis: "NAVAL_USAGE", expectation: "NORMAL" },
      { axis: "STRATEGIC_WEAPON_USAGE", expectation: "LOW" },
      { axis: "EXPRESSION_SIGNATURE", expectation: "VERY_HIGH" },
    ],
    customChecks: [
      "KAIKI_AVOIDS_FAIR_EXPENSIVE_WARS",
      "KAIKI_DISENGAGES_WHEN_PROFIT_CASE_COLLAPSES",
      "KAIKI_REMAINS_DISTINCT_FROM_ASKELADD",
    ],
  },
} as const;

export const OFFICIAL_AI_CHARACTER_CONFIGURATIONS = [
  OFFICIAL_AI_BASELINE_CHARACTER_PROFILE,
  THORFINN_KARLSEFNI,
  ASKELADD,
  REINHARD_VON_LOHENGRAMM,
  YANG_WEN_LI,
  FRIEREN,
  UBEL,
  TANYA_DEGURECHAFF,
  KISS_SHOT_ACEROLA_ORION_HEART_UNDER_BLADE,
  HANEKAWA_TSUBASA,
  KAIKI_DEISHUU,
] as const;
