// Documentation entry point: docs/official-ai/README.md
// Specific owners: docs/official-ai/OFFICIAL_AI_ORIGIN_CONFIGURATIONS.md
//                  docs/official-ai/OFFICIAL_AI_ORIGIN_SUPPORT.md
// Gameplay owner:  docs/OFFICIAL_ORIGINS.md
//
// Open Fufu Official-AI named-Origin configuration.
//
// DESIGN-TIME SOURCE OF TRUTH.
// `traitIds` mirror OFFICIAL_ORIGINS.md and must validate exactly against that
// content registry. `requiredCombinationSupportIds` asserts which reusable
// combination-support entries must compose for each Origin. `profileAssertions`
// are intentionally partial golden assertions, not a duplicate full derived
// OriginStrategicProfile. `originSpecificSupport` remains null unless a named
// Origin needs support that cannot be generalized to its trait combination.
//
// New accepted Origin batches are appended to this file. Do not create batch
// shards solely for incremental authoring.

export const OFFICIAL_AI_ORIGIN_CONFIGURATIONS = [
  {
    originId: "O08",
    traitIds: ["P06", "P09"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["TRADE", "FORTIFICATION", "INFRASTRUCTURE"],
      requiredAffordances: ["SCALE_TRADE", "HOLD_GROUND"],
      requiredCautions: [],
    },
    validationFocus: [
      "FAST_TRADE_THROUGHPUT",
      "IMPROVED_FORT_INVESTMENT",
      "NO_FALSE_SPECIALIST_REQUIREMENT",
    ],
  },
  {
    originId: "O09",
    traitIds: ["P01", "P06", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["EXPANSION", "TRADE", "POSITIONAL_CONTROL"],
      requiredAffordances: ["SCALE_TRADE"],
      requiredCautions: [],
    },
    validationFocus: [
      "LARGER_INITIAL_TERRITORY_SPAWN",
      "FAST_TRADE_THROUGHPUT",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O10",
    traitIds: ["P09", "P13", "P15", "N02"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["FORTIFICATION", "POSITIONAL_CONTROL", "SPECIALIZATION"],
      requiredAffordances: ["HOLD_GROUND", "EXPLOIT_TERRAIN", "CREATE_BREAKTHROUGH"],
      requiredCautions: ["TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "FORT_MOUNTAIN_DEFENSE_VALUE",
      "HIGHLAND_OFFENSIVE_STAGING",
      "PLAINS_OFFENSE_PENALTY",
      "NO_BLIND_TERRAIN_BONUS_CHASING",
    ],
  },
  {
    originId: "O11",
    traitIds: ["P08", "P06", "P07", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["TRADE", "INDUSTRIALIZATION", "ECONOMIC_COMPOUNDING"],
      requiredAffordances: ["SCALE_TRADE", "SCALE_INDUSTRY", "SCALE_ECONOMY"],
      requiredCautions: [],
    },
    validationFocus: [
      "FULL_WARTIME_TRADE_VALUE",
      "FAST_TRADE_THROUGHPUT",
      "INCREASED_TRAIN_THROUGHPUT",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O12",
    traitIds: ["P23", "P22", "N01"],
    requiredCombinationSupportIds: ["ELITE_SINGLE_FLAGSHIP_PROGRESSION"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["NAVAL_PROJECTION", "DECISIVE_FORCE", "FORCE_PRESERVATION", "SPECIALIZATION"],
      requiredAffordances: ["PROJECT_FROM_SEA", "FIGHT_FROM_RANGE", "PRESERVE_FORCE"],
      requiredCautions: ["REQUIRES_VETERANCY", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "ONE_WARSHIP_OWNERSHIP_CAP",
      "FLAGSHIP_THEATER_ALLOCATION",
      "EXTENDED_VETERANCY_PROGRESSION",
      "VETERAN_FLAGSHIP_PRESERVATION_VALUE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O13",
    traitIds: ["P25"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["DECISIVE_FORCE", "ESCALATION", "DETERRENCE", "TERRITORIAL_SHAPING", "SPECIALIZATION"],
      requiredAffordances: ["DENY_AREA", "SHAPE_TERRITORY", "FORCE_ENEMY_RESPONSE"],
      requiredCautions: ["HIGH_UPFRONT_COST"],
    },
    validationFocus: [
      "ATOM_AND_MIRV_UNAVAILABLE",
      "HYDROGEN_ONLY_PLANNING",
      "LARGER_HYDROGEN_AREA",
      "HIGHER_HYDROGEN_COST",
    ],
  },
  {
    originId: "O14",
    traitIds: ["P39"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["DISTRIBUTED_PLAY", "POSITIONAL_CONTROL", "EXPANSION", "SPECIALIZATION"],
      requiredAffordances: ["DISTRIBUTE_START", "MULTI_THEATER_ACCESS"],
      requiredCautions: ["SPLIT_FRONT_RISK", "ISOLATED_CORE_RISK"],
    },
    validationFocus: [
      "STRATEGIC_TWO_HALF_AREA_INFLUENCE_REGIONS",
      "TWO_EXACT_ORIGINS_ALL_MODES",
      "RANDOM_TWO_ORIGIN_RESOLUTION",
      "FIXED_REQUIRES_TWO_AUTHORED_ORIGINS",
      "SPLIT_INITIAL_TERRITORY",
      "ONE_GLOBAL_STARTING_POPULATION_POOL",
      "STRATEGIC_PAIRWISE_SPAWN_EVALUATION",
    ],
  },
  {
    originId: "O15",
    traitIds: ["P50", "P51"],
    requiredCombinationSupportIds: ["DUAL_GENERAL_SUPPORT_NETWORK"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["INFRASTRUCTURE", "POSITIONAL_CONTROL", "FORTIFICATION"],
      requiredAffordances: ["HOLD_GROUND", "CREATE_BREAKTHROUGH", "PROTECT_HIGH_VALUE_ASSET"],
      requiredCautions: [],
    },
    validationFocus: [
      "FORT_OFFENSIVE_SUPPORT",
      "COMMAND_POST_DEFENSIVE_SUPPORT",
      "DUAL_SUPPORT_NETWORK_PLACEMENT",
      "OFFENSE_DEFENSE_COVERAGE_TRADEOFF",
    ],
  },
  {
    originId: "O16",
    traitIds: ["P38"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["FORCE_PRESERVATION", "ATTRITION", "SACRIFICE"],
      requiredAffordances: ["PRESERVE_FORCE", "TRADE_GROUND_FOR_CASUALTIES", "LURE_OVEREXTENSION"],
      requiredCautions: [],
    },
    validationFocus: [
      "AUTOMATIC_DEFENDER_SURVIVES_CAPTURE",
      "TERRITORY_LOSS_WITHOUT_DEFENDER_LOSS_FORECAST",
      "ELASTIC_DEFENSE_PLANS_AVAILABLE_AT_CAPABLE_TIERS",
    ],
  },
  {
    originId: "O17",
    traitIds: ["P49", "P45", "N02"],
    requiredCombinationSupportIds: ["LAYERED_COUNTERINTELLIGENCE"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["INFORMATION", "POSITIONAL_CONTROL", "FORCE_PRESERVATION", "SPECIALIZATION"],
      requiredAffordances: ["GAIN_INFORMATION_ADVANTAGE", "PROTECT_HIGH_VALUE_ASSET"],
      requiredCautions: ["TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "OBSERVATION_POST_BLACKOUT_ROLE",
      "NO_SELF_TACTICAL_OBSERVATION_FROM_POSTS",
      "FOREST_INTERIOR_CONCEALMENT",
      "LAYERED_CONCEALMENT_POSITIONING",
      "PLAINS_OFFENSE_PENALTY",
    ],
  },

  // Second 10 in canonical library/UI order.
  {
    originId: "O01",
    traitIds: ["P38", "P09", "P13", "N02", "N13"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["FORCE_PRESERVATION", "FORTIFICATION", "POSITIONAL_CONTROL", "ATTRITION"],
      requiredAffordances: ["PRESERVE_FORCE", "HOLD_GROUND", "EXPLOIT_TERRAIN", "TRADE_GROUND_FOR_CASUALTIES"],
      requiredCautions: ["TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "AUTOMATIC_DEFENDER_SURVIVES_CAPTURE",
      "IMPROVED_FORT_INVESTMENT",
      "MOUNTAIN_DEFENSE_VALUE",
      "PLAINS_OFFENSE_PENALTY",
      "HALF_TRANSPORT_POPULATION_DIES_ON_LANDING",
    ],
  },
  {
    originId: "O18",
    traitIds: ["P38", "P04", "P13", "N13"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["FORCE_PRESERVATION", "ATTRITION", "FORTIFICATION", "POSITIONAL_CONTROL"],
      requiredAffordances: ["PRESERVE_FORCE", "RETALIATE_EFFICIENTLY", "HOLD_GROUND", "EXPLOIT_TERRAIN"],
      requiredCautions: ["TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "AUTOMATIC_DEFENDER_SURVIVES_CAPTURE",
      "FIXED_RESPONSE_SIDE_COUNTER_RESPONSE",
      "MOUNTAIN_DEFENSE_VALUE",
      "HALF_TRANSPORT_POPULATION_DIES_ON_LANDING",
    ],
  },
  {
    originId: "O19",
    traitIds: ["P04", "P08", "P38", "N07"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["FORCE_PRESERVATION", "ATTRITION", "TRADE", "ECONOMIC_COMPOUNDING", "SPECIALIZATION", "INFRASTRUCTURE"],
      requiredAffordances: ["PRESERVE_FORCE", "RETALIATE_EFFICIENTLY", "SCALE_TRADE", "TRADE_GROUND_FOR_CASUALTIES"],
      requiredCautions: ["EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "FIXED_RESPONSE_SIDE_COUNTER_RESPONSE",
      "FULL_WARTIME_TRADE_VALUE",
      "AUTOMATIC_DEFENDER_SURVIVES_CAPTURE",
      "ONE_PER_STRUCTURE_TYPE_LIMIT",
      "UNIQUE_STRUCTURE_PLACEMENT_VALUE",
    ],
  },
  {
    originId: "O20",
    traitIds: ["P08", "P02", "P21", "N07"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["TRADE", "ECONOMIC_COMPOUNDING", "GROWTH", "INFRASTRUCTURE", "SPECIALIZATION", "POSITIONAL_CONTROL"],
      requiredAffordances: ["SCALE_TRADE", "SCALE_GROWTH"],
      requiredCautions: ["HIGH_LIQUIDITY_NEED", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "FULL_WARTIME_TRADE_VALUE",
      "WIDE_POPULATION_UTILIZATION_GROWTH",
      "FIRST_STRUCTURE_PURCHASE_ZERO_FFY_CONSUMPTION",
      "FIRST_PURCHASE_STILL_REQUIRES_AFFORDABILITY",
      "ONE_PER_STRUCTURE_TYPE_LIMIT",
    ],
  },
  {
    originId: "O21",
    traitIds: ["P38", "P02", "N12", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["FORCE_PRESERVATION", "ATTRITION", "SACRIFICE", "GROWTH", "ECONOMIC_COMPOUNDING"],
      requiredAffordances: ["PRESERVE_FORCE", "TRADE_GROUND_FOR_CASUALTIES", "SCALE_GROWTH"],
      requiredCautions: [],
    },
    validationFocus: [
      "AUTOMATIC_DEFENDER_SURVIVES_CAPTURE",
      "WIDE_POPULATION_UTILIZATION_GROWTH",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
      "NO_PHANTOM_WARSHIP_DEPENDENT_SUPPORT",
    ],
  },
  {
    originId: "O22",
    traitIds: ["P19", "P03", "P15", "N01", "N04"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["DECISIVE_FORCE", "DISTRIBUTED_PLAY", "EXPANSION", "SIEGE", "POSITIONAL_CONTROL", "SPECIALIZATION"],
      requiredAffordances: ["CREATE_BREAKTHROUGH", "SIEGE_STATIC_POSITIONS", "EXPLOIT_TERRAIN"],
      requiredCautions: ["SPLIT_FRONT_RISK", "TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "CONTACT_COUNT_OFFENSE_SCALING",
      "IGNORE_ENEMY_FORT_DEFENSIVE_PRESSURE",
      "HIGHLAND_OFFENSIVE_STAGING",
      "REDUCED_CITY_GROWTH_FORECAST",
      "REDUCED_MOUNTAIN_FFY_VALUE",
    ],
  },
  {
    originId: "O04",
    traitIds: ["P05", "P34", "P15", "N09", "N02"],
    requiredCombinationSupportIds: ["CONQUEST_FACTORY_SNOWBALL", "CONQUEST_ONLY_INDUSTRY"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["RAIDING", "INDUSTRIALIZATION", "ECONOMIC_COMPOUNDING", "EXPANSION", "DECISIVE_FORCE", "SPECIALIZATION"],
      requiredAffordances: ["RAID_INFRASTRUCTURE", "SCALE_INDUSTRY", "SCALE_ECONOMY", "CREATE_BREAKTHROUGH", "EXPLOIT_TERRAIN"],
      requiredCautions: ["INFRASTRUCTURE_DEPENDENCE", "TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "CONQUEST_STRUCTURE_FFY_REWARD",
      "CONQUERED_FACTORY_DOUBLE_EFFECT",
      "FACTORY_CONSTRUCTION_UNAVAILABLE",
      "CONQUEST_FACTORY_COMBINED_SNOWBALL_VALUE",
      "CONQUEST_ONLY_FACTORY_ACQUISITION_PRIORITY",
      "PLAINS_OFFENSE_PENALTY",
    ],
  },
  {
    originId: "O23",
    traitIds: ["P05", "P08", "P06", "N13"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["RAIDING", "EXPANSION", "ECONOMIC_COMPOUNDING", "TRADE", "MOBILITY"],
      requiredAffordances: ["RAID_INFRASTRUCTURE", "SCALE_TRADE"],
      requiredCautions: [],
    },
    validationFocus: [
      "CONQUEST_STRUCTURE_FFY_REWARD",
      "FULL_WARTIME_TRADE_VALUE",
      "FAST_TRADE_THROUGHPUT",
      "HALF_TRANSPORT_POPULATION_DIES_ON_LANDING",
    ],
  },
  {
    originId: "O24",
    traitIds: ["P43", "P15", "P19", "N12", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["SIEGE", "DECISIVE_FORCE", "POSITIONAL_CONTROL", "SPECIALIZATION", "DISTRIBUTED_PLAY", "EXPANSION"],
      requiredAffordances: ["FIGHT_FROM_RANGE", "SIEGE_STATIC_POSITIONS", "CREATE_BREAKTHROUGH", "FORCE_ENEMY_RESPONSE", "EXPLOIT_TERRAIN"],
      requiredCautions: ["HIGH_UPFRONT_COST", "LOW_MOBILITY", "LONG_RELOAD", "CLOSE_RANGE_VULNERABILITY", "EXPENSIVE_FAILURE", "TERRAIN_DEPENDENCE", "SPLIT_FRONT_RISK"],
    },
    validationFocus: [
      "HEAVY_ARTILLERY_REPLACES_TANKS",
      "HEAVY_ARTILLERY_STANDOFF_POSITIONING",
      "HIGHLAND_OFFENSIVE_STAGING",
      "CONTACT_COUNT_OFFENSE_SCALING",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O25",
    traitIds: ["P03", "P43", "P15", "N12", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["SIEGE", "DECISIVE_FORCE", "POSITIONAL_CONTROL", "SPECIALIZATION"],
      requiredAffordances: ["SIEGE_STATIC_POSITIONS", "CREATE_BREAKTHROUGH", "FIGHT_FROM_RANGE", "FORCE_ENEMY_RESPONSE", "EXPLOIT_TERRAIN"],
      requiredCautions: ["HIGH_UPFRONT_COST", "LOW_MOBILITY", "LONG_RELOAD", "CLOSE_RANGE_VULNERABILITY", "EXPENSIVE_FAILURE", "TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "IGNORE_ENEMY_FORT_DEFENSIVE_PRESSURE",
      "HEAVY_ARTILLERY_REPLACES_TANKS",
      "HEAVY_ARTILLERY_STANDOFF_POSITIONING",
      "HIGHLAND_OFFENSIVE_STAGING",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },

  // Third 10 in canonical library/UI order.
  {
    originId: "O26",
    traitIds: ["P05", "P43", "P04", "N12", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["RAIDING", "EXPANSION", "ECONOMIC_COMPOUNDING", "SIEGE", "DECISIVE_FORCE", "POSITIONAL_CONTROL", "SPECIALIZATION", "ATTRITION", "FORCE_PRESERVATION"],
      requiredAffordances: ["RAID_INFRASTRUCTURE", "FIGHT_FROM_RANGE", "SIEGE_STATIC_POSITIONS", "CREATE_BREAKTHROUGH", "RETALIATE_EFFICIENTLY", "PRESERVE_FORCE"],
      requiredCautions: ["HIGH_UPFRONT_COST", "LOW_MOBILITY", "LONG_RELOAD", "CLOSE_RANGE_VULNERABILITY", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "CONQUEST_STRUCTURE_FFY_REWARD",
      "HEAVY_ARTILLERY_REPLACES_TANKS",
      "HEAVY_ARTILLERY_STANDOFF_POSITIONING",
      "FIXED_RESPONSE_SIDE_COUNTER_RESPONSE",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O27",
    traitIds: ["P43", "P25", "N12", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["SIEGE", "DECISIVE_FORCE", "POSITIONAL_CONTROL", "SPECIALIZATION", "ESCALATION", "DETERRENCE", "TERRITORIAL_SHAPING"],
      requiredAffordances: ["FIGHT_FROM_RANGE", "SIEGE_STATIC_POSITIONS", "CREATE_BREAKTHROUGH", "DENY_AREA", "SHAPE_TERRITORY", "FORCE_ENEMY_RESPONSE"],
      requiredCautions: ["HIGH_UPFRONT_COST", "LOW_MOBILITY", "LONG_RELOAD", "CLOSE_RANGE_VULNERABILITY", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "HEAVY_ARTILLERY_REPLACES_TANKS",
      "HEAVY_ARTILLERY_STANDOFF_POSITIONING",
      "HYDROGEN_ONLY_PLANNING",
      "LARGER_MORE_EXPENSIVE_HYDROGEN_STRIKES",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O28",
    traitIds: ["P25", "P10", "P40", "N07"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["DECISIVE_FORCE", "ESCALATION", "DETERRENCE", "TERRITORIAL_SHAPING", "SPECIALIZATION", "FORTIFICATION", "POSITIONAL_CONTROL", "INFRASTRUCTURE"],
      requiredAffordances: ["DENY_AREA", "SHAPE_TERRITORY", "FORCE_ENEMY_RESPONSE", "REDUCE_INTERCEPTION_WINDOW", "INTERCEPT_OVER_LARGE_AREA", "PROTECT_HIGH_VALUE_ASSET"],
      requiredCautions: ["HIGH_UPFRONT_COST", "LOW_THROUGHPUT", "BAITABLE_DEFENSE", "LONG_RELOAD", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "HYDROGEN_ONLY_PLANNING",
      "DOUBLE_STRATEGIC_WARHEAD_SPEED",
      "GIANT_SINGLE_CHARGE_SAM_SEMANTICS",
      "ONE_PER_STRUCTURE_TYPE_LIMIT",
      "UNIQUE_SILO_AND_SAM_PLACEMENT_VALUE",
    ],
  },
  {
    originId: "O29",
    traitIds: ["P43", "P44", "N12", "N01"],
    requiredCombinationSupportIds: ["RADIOACTIVE_HEAVY_ARTILLERY"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["SIEGE", "DECISIVE_FORCE", "POSITIONAL_CONTROL", "SPECIALIZATION", "ATTRITION", "TERRITORIAL_SHAPING"],
      requiredAffordances: ["FIGHT_FROM_RANGE", "SIEGE_STATIC_POSITIONS", "CREATE_BREAKTHROUGH", "DENY_AREA", "SHAPE_TERRITORY", "CUT_CONNECTIVITY", "ERODE_TERRITORY_AT_RANGE"],
      requiredCautions: ["HIGH_UPFRONT_COST", "LOW_MOBILITY", "LONG_RELOAD", "CLOSE_RANGE_VULNERABILITY", "EXPENSIVE_FAILURE", "SELF_GEOMETRY_RISK"],
    },
    validationFocus: [
      "HEAVY_ARTILLERY_REPLACES_TANKS",
      "RADIOACTIVE_POPULATION_ATTACKS",
      "STANDOFF_FALLOUT_BOMBARDMENT",
      "STANDOFF_TERRITORY_EROSION_FORECAST",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O30",
    traitIds: ["P43", "P10", "P20", "N12", "N03"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["SIEGE", "DECISIVE_FORCE", "POSITIONAL_CONTROL", "SPECIALIZATION", "DETERRENCE", "ESCALATION", "INFRASTRUCTURE"],
      requiredAffordances: ["FIGHT_FROM_RANGE", "SIEGE_STATIC_POSITIONS", "CREATE_BREAKTHROUGH", "FORCE_ENEMY_RESPONSE", "REDUCE_INTERCEPTION_WINDOW"],
      requiredCautions: ["HIGH_UPFRONT_COST", "LOW_MOBILITY", "LONG_RELOAD", "CLOSE_RANGE_VULNERABILITY", "EXPENSIVE_FAILURE", "TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "FREE_STARTING_MISSILE_SILO",
      "DOUBLE_STRATEGIC_WARHEAD_SPEED",
      "HEAVY_ARTILLERY_REPLACES_TANKS",
      "HEAVY_ARTILLERY_STANDOFF_POSITIONING",
      "WARSHIP_BUILD_UNAVAILABLE",
      "DESERT_DEFENSE_PENALTY",
    ],
  },
  {
    originId: "O31",
    traitIds: ["P20", "P25", "N11"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["DETERRENCE", "ESCALATION", "INFRASTRUCTURE", "DECISIVE_FORCE", "TERRITORIAL_SHAPING", "SPECIALIZATION"],
      requiredAffordances: ["DENY_AREA", "SHAPE_TERRITORY", "FORCE_ENEMY_RESPONSE"],
      requiredCautions: ["HIGH_UPFRONT_COST", "SELF_GEOMETRY_RISK", "INFRASTRUCTURE_DEPENDENCE"],
    },
    validationFocus: [
      "FREE_STARTING_MISSILE_SILO",
      "HYDROGEN_ONLY_PLANNING",
      "LARGER_MORE_EXPENSIVE_HYDROGEN_STRIKES",
      "SAM_COVERAGE_ZEROES_FFY_EVENTS",
      "SAM_DEFENSE_VS_ECONOMY_GEOMETRY",
    ],
  },
  {
    originId: "O32",
    traitIds: ["P11", "P40", "N11"],
    requiredCombinationSupportIds: ["POPULATION_SCALED_GIANT_SAM_NETWORK"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["GROWTH", "FORTIFICATION", "INFRASTRUCTURE", "DETERRENCE", "SPECIALIZATION", "POSITIONAL_CONTROL"],
      requiredAffordances: ["INTERCEPT_OVER_LARGE_AREA", "PROTECT_HIGH_VALUE_ASSET"],
      requiredCautions: ["LOW_THROUGHPUT", "BAITABLE_DEFENSE", "LONG_RELOAD", "SELF_GEOMETRY_RISK", "INFRASTRUCTURE_DEPENDENCE"],
    },
    validationFocus: [
      "POPULATION_UNLOCKED_ZERO_FFY_SAM_SLOTS",
      "GIANT_SINGLE_CHARGE_SAM_SEMANTICS",
      "POPULATION_SCALED_GIANT_SAM_NETWORK_VALUE",
      "SAM_COVERAGE_ZEROES_FFY_EVENTS",
      "SAM_NETWORK_DEFENSE_VS_ECONOMY_GEOMETRY",
    ],
  },
  {
    originId: "O33",
    traitIds: ["P44", "P16", "P35", "N12", "N01"],
    requiredCombinationSupportIds: ["REVERSIBLE_SCORCHED_EARTH", "RADIOACTIVE_FALLOUT_ADVANCE"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["ATTRITION", "TERRITORIAL_SHAPING", "POSITIONAL_CONTROL", "SIEGE", "EXPANSION", "SACRIFICE"],
      requiredAffordances: ["DENY_AREA", "SHAPE_TERRITORY", "CUT_CONNECTIVITY", "FORCE_ENEMY_RESPONSE"],
      requiredCautions: ["SELF_GEOMETRY_RISK", "REQUIRES_GIVING_GROUND"],
    },
    validationFocus: [
      "RADIOACTIVE_POPULATION_ATTACKS",
      "IGNORE_FALLOUT_CAPTURE_RESISTANCE",
      "RELINQUISHED_CELLS_BECOME_FALLOUT",
      "REVERSIBLE_SCORCHED_EARTH_VALUE",
      "RADIOACTIVE_FALLOUT_FOLLOWUP_ADVANCE",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O34",
    traitIds: ["P44", "P16", "P47", "N12", "N01"],
    requiredCombinationSupportIds: ["RADIOACTIVE_FALLOUT_ADVANCE"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["ATTRITION", "TERRITORIAL_SHAPING", "POSITIONAL_CONTROL", "SIEGE", "EXPANSION", "SACRIFICE"],
      requiredAffordances: ["DENY_AREA", "SHAPE_TERRITORY", "CUT_CONNECTIVITY", "FORCE_ENEMY_RESPONSE", "TRADE_GROUND_FOR_CASUALTIES", "LURE_OVEREXTENSION"],
      requiredCautions: ["SELF_GEOMETRY_RISK", "TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "RADIOACTIVE_POPULATION_ATTACKS",
      "IGNORE_FALLOUT_CAPTURE_RESISTANCE",
      "RADIOACTIVE_FALLOUT_FOLLOWUP_ADVANCE",
      "ENEMY_MARSH_CAPTURE_POPULATION_PENALTY",
      "MARSH_ATTRITION_DEFENSE_VALUE",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O36",
    traitIds: ["P46", "P48", "P16", "P36", "N13"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["INFRASTRUCTURE", "POSITIONAL_CONTROL", "SPECIALIZATION", "FORTIFICATION", "GROWTH", "EXPANSION", "FORCE_PRESERVATION"],
      requiredAffordances: ["EXPLOIT_TERRAIN", "SCALE_GROWTH", "EXPAND_CHEAPLY", "EXPAND_WITH_LOW_POPULATION", "PRESERVE_FORCE"],
      requiredCautions: ["TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "TUNDRA_STRUCTURE_BUILDABILITY",
      "SHALLOW_WATER_CAPACITY_VALUE",
      "IGNORE_FALLOUT_CAPTURE_RESISTANCE",
      "HALF_COST_NEUTRAL_SETTLEMENT",
      "HALF_TRANSPORT_POPULATION_DIES_ON_LANDING",
      "MULTI_TERRAIN_EXPANSION_VALUE",
    ],
  },

  // Fourth 10 in canonical library/UI order.
  {
    originId: "O37",
    traitIds: ["P49", "P45", "P17", "N07"],
    requiredCombinationSupportIds: ["LAYERED_COUNTERINTELLIGENCE"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["INFORMATION", "POSITIONAL_CONTROL", "FORCE_PRESERVATION", "SPECIALIZATION", "ECONOMIC_COMPOUNDING", "INFRASTRUCTURE"],
      requiredAffordances: ["GAIN_INFORMATION_ADVANTAGE", "PROTECT_HIGH_VALUE_ASSET", "BUILD_HIGH_LEVEL_INFRASTRUCTURE"],
      requiredCautions: ["TERRAIN_DEPENDENCE", "INFRASTRUCTURE_DEPENDENCE", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "OBSERVATION_POST_BLACKOUT_ROLE",
      "FOREST_INTERIOR_CONCEALMENT",
      "LAYERED_CONCEALMENT_POSITIONING",
      "STRUCTURE_COUNT_UPGRADE_DISCOUNT",
      "ONE_PER_STRUCTURE_TYPE_LIMIT",
      "UPGRADE_DISCOUNT_USES_ACTUAL_CONSTRAINED_STRUCTURE_COUNT",
    ],
  },
  {
    originId: "O38",
    traitIds: ["P17", "P21", "P04", "N01", "N04"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["ECONOMIC_COMPOUNDING", "INFRASTRUCTURE", "SPECIALIZATION", "ATTRITION", "FORCE_PRESERVATION"],
      requiredAffordances: ["BUILD_HIGH_LEVEL_INFRASTRUCTURE", "RETALIATE_EFFICIENTLY", "PRESERVE_FORCE"],
      requiredCautions: ["HIGH_LIQUIDITY_NEED", "TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "STRUCTURE_COUNT_UPGRADE_DISCOUNT",
      "FIRST_STRUCTURE_PURCHASE_ZERO_FFY_CONSUMPTION",
      "FIRST_PURCHASE_STILL_REQUIRES_AFFORDABILITY",
      "FIXED_RESPONSE_SIDE_COUNTER_RESPONSE",
      "REDUCED_CITY_GROWTH_FORECAST",
      "REDUCED_MOUNTAIN_FFY_VALUE",
    ],
  },
  {
    originId: "O02",
    traitIds: ["P08", "P06", "P07", "P41", "N07"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["TRADE", "ECONOMIC_COMPOUNDING", "MOBILITY", "INDUSTRIALIZATION", "INFRASTRUCTURE", "GROWTH", "SPECIALIZATION", "POSITIONAL_CONTROL"],
      requiredAffordances: ["SCALE_TRADE", "SCALE_INDUSTRY", "SCALE_ECONOMY", "BUILD_HIGH_LEVEL_INFRASTRUCTURE", "SCALE_GROWTH"],
      requiredCautions: ["HIGH_UPFRONT_COST", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "FULL_WARTIME_TRADE_VALUE",
      "FAST_TRADE_THROUGHPUT",
      "INCREASED_TRAIN_THROUGHPUT",
      "DIRECT_LEVEL5_CITY_PURCHASE",
      "ONE_PER_STRUCTURE_TYPE_LIMIT",
      "UNIQUE_CITY_PLACEMENT_VALUE",
    ],
  },
  {
    originId: "O39",
    traitIds: ["P17", "P21", "P41", "N07"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["ECONOMIC_COMPOUNDING", "INFRASTRUCTURE", "SPECIALIZATION", "GROWTH", "POSITIONAL_CONTROL"],
      requiredAffordances: ["BUILD_HIGH_LEVEL_INFRASTRUCTURE", "SCALE_GROWTH"],
      requiredCautions: ["HIGH_LIQUIDITY_NEED", "HIGH_UPFRONT_COST", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "STRUCTURE_COUNT_UPGRADE_DISCOUNT",
      "FIRST_STRUCTURE_PURCHASE_ZERO_FFY_CONSUMPTION",
      "FIRST_PURCHASE_STILL_REQUIRES_AFFORDABILITY",
      "DIRECT_LEVEL5_CITY_PURCHASE",
      "FIRST_CITY_DIRECT_LEVEL5_ZERO_FFY_WHEN_AFFORDABLE",
      "ONE_PER_STRUCTURE_TYPE_LIMIT",
    ],
  },
  {
    originId: "O40",
    traitIds: ["P02", "P17", "P07", "N07"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["GROWTH", "ECONOMIC_COMPOUNDING", "FORCE_PRESERVATION", "INFRASTRUCTURE", "SPECIALIZATION", "INDUSTRIALIZATION", "POSITIONAL_CONTROL"],
      requiredAffordances: ["SCALE_GROWTH", "BUILD_HIGH_LEVEL_INFRASTRUCTURE", "SCALE_INDUSTRY", "SCALE_ECONOMY"],
      requiredCautions: ["EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "WIDE_POPULATION_UTILIZATION_GROWTH",
      "STRUCTURE_COUNT_UPGRADE_DISCOUNT",
      "INCREASED_TRAIN_THROUGHPUT",
      "ONE_PER_STRUCTURE_TYPE_LIMIT",
      "UPGRADE_DISCOUNT_USES_ACTUAL_CONSTRAINED_STRUCTURE_COUNT",
    ],
  },
  {
    originId: "O41",
    traitIds: ["P17", "P07", "P41", "N13"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["ECONOMIC_COMPOUNDING", "INFRASTRUCTURE", "SPECIALIZATION", "INDUSTRIALIZATION", "GROWTH"],
      requiredAffordances: ["BUILD_HIGH_LEVEL_INFRASTRUCTURE", "SCALE_INDUSTRY", "SCALE_ECONOMY", "SCALE_GROWTH"],
      requiredCautions: ["HIGH_UPFRONT_COST"],
    },
    validationFocus: [
      "STRUCTURE_COUNT_UPGRADE_DISCOUNT",
      "INCREASED_TRAIN_THROUGHPUT",
      "DIRECT_LEVEL5_CITY_PURCHASE",
      "NO_PHANTOM_CITY_UPGRADE_PATH_AFTER_DIRECT_LEVEL5_PURCHASE",
      "HALF_TRANSPORT_POPULATION_DIES_ON_LANDING",
    ],
  },
  {
    originId: "O42",
    traitIds: ["P01", "P17", "P07", "N01", "N04"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["EXPANSION", "POSITIONAL_CONTROL", "ECONOMIC_COMPOUNDING", "INFRASTRUCTURE", "SPECIALIZATION", "INDUSTRIALIZATION"],
      requiredAffordances: ["BUILD_HIGH_LEVEL_INFRASTRUCTURE", "SCALE_INDUSTRY", "SCALE_ECONOMY"],
      requiredCautions: ["TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "LARGER_INITIAL_TERRITORY_SPAWN",
      "STRUCTURE_COUNT_UPGRADE_DISCOUNT",
      "INCREASED_TRAIN_THROUGHPUT",
      "REDUCED_CITY_GROWTH_FORECAST",
      "REDUCED_MOUNTAIN_FFY_VALUE",
    ],
  },
  {
    originId: "O07",
    traitIds: ["P30", "P06", "P31", "N13"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["RAIDING", "MOBILITY", "NAVAL_PROJECTION", "ECONOMIC_COMPOUNDING", "SPECIALIZATION", "TRADE", "FORCE_PRESERVATION", "FORTIFICATION", "INFRASTRUCTURE"],
      requiredAffordances: ["SCALE_ECONOMY", "SCALE_TRADE", "PRESERVE_FORCE", "PROJECT_FROM_SEA"],
      requiredCautions: ["INFRASTRUCTURE_DEPENDENCE", "COAST_DEPENDENCE"],
    },
    validationFocus: [
      "PIRACY_ONLY_WARSHIP_ROLE",
      "NO_NAVAL_GUNFIRE_AGAINST_SHIPS",
      "FAST_PIRACY_PATROLS",
      "FAST_TRADE_THROUGHPUT",
      "PORT_REPAIR_SUSTAINMENT",
      "HALF_TRANSPORT_POPULATION_DIES_ON_LANDING",
    ],
  },
  {
    originId: "O05",
    traitIds: ["P37", "P32", "P12", "N12", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["AMPHIBIOUS", "FORTIFICATION", "NAVAL_PROJECTION", "POSITIONAL_CONTROL", "FORCE_PRESERVATION", "INFRASTRUCTURE", "MOBILITY"],
      requiredAffordances: ["FORTIFY_BEACHHEAD", "CREATE_SECOND_FRONT", "PROJECT_FROM_SEA", "HOLD_GROUND", "PRESERVE_FORCE"],
      requiredCautions: ["HIGH_UPFRONT_COST", "EXPENSIVE_FAILURE", "COAST_DEPENDENCE", "INFRASTRUCTURE_DEPENDENCE"],
    },
    validationFocus: [
      "FORTIFIED_LANDING_CREATES_LEVEL1_FORT",
      "EXTRA_EMBARKATION_FFY_COST",
      "PORT_ONLY_ARMORED_TRANSPORTS",
      "ARMORED_TRANSPORT_SURVIVABILITY",
      "FASTER_TRANSPORT_TRANSIT",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O43",
    traitIds: ["P23", "P22", "P31", "N07"],
    requiredCombinationSupportIds: ["ELITE_SINGLE_FLAGSHIP_PROGRESSION"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["NAVAL_PROJECTION", "SPECIALIZATION", "FORCE_PRESERVATION", "DECISIVE_FORCE", "FORTIFICATION", "INFRASTRUCTURE", "POSITIONAL_CONTROL"],
      requiredAffordances: ["PROJECT_FROM_SEA", "FIGHT_FROM_RANGE", "PRESERVE_FORCE"],
      requiredCautions: ["EXPENSIVE_FAILURE", "REQUIRES_VETERANCY", "INFRASTRUCTURE_DEPENDENCE", "COAST_DEPENDENCE"],
    },
    validationFocus: [
      "ONE_WARSHIP_OWNERSHIP_CAP",
      "EXTENDED_VETERANCY_PROGRESSION",
      "VETERAN_FLAGSHIP_PRESERVATION_VALUE",
      "PORT_REPAIR_SUSTAINMENT",
      "ONE_PER_STRUCTURE_TYPE_LIMIT",
      "UNIQUE_PORT_PLACEMENT_VALUE",
    ],
  },

  // Final 9 in canonical library/UI order.
  {
    originId: "O03",
    traitIds: ["P02", "P07", "P33", "N01", "N12"],
    requiredCombinationSupportIds: ["TRAIN_POPULATION_ENGINE_ACCELERATION"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["GROWTH", "ECONOMIC_COMPOUNDING", "FORCE_PRESERVATION", "INDUSTRIALIZATION", "INFRASTRUCTURE"],
      requiredAffordances: ["SCALE_GROWTH", "SCALE_INDUSTRY", "SCALE_ECONOMY", "BUILD_HIGH_LEVEL_INFRASTRUCTURE"],
      requiredCautions: ["INFRASTRUCTURE_DEPENDENCE"],
    },
    validationFocus: [
      "WIDE_POPULATION_UTILIZATION_GROWTH",
      "INCREASED_TRAIN_THROUGHPUT",
      "TRAIN_CITY_POPULATION_ENGINE",
      "TRAIN_POPULATION_ENGINE_ACCELERATION",
      "REDUCED_CITY_GROWTH_FORECAST",
      "WARSHIP_BUILD_UNAVAILABLE",
    ],
  },
  {
    originId: "O44",
    traitIds: ["P21", "P36", "P01", "N12", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["INFRASTRUCTURE", "ECONOMIC_COMPOUNDING", "SPECIALIZATION", "EXPANSION", "GROWTH", "FORCE_PRESERVATION", "POSITIONAL_CONTROL"],
      requiredAffordances: ["EXPAND_CHEAPLY", "EXPAND_WITH_LOW_POPULATION", "PRESERVE_FORCE"],
      requiredCautions: ["HIGH_LIQUIDITY_NEED"],
    },
    validationFocus: [
      "FIRST_STRUCTURE_PURCHASE_ZERO_FFY_CONSUMPTION",
      "FIRST_PURCHASE_STILL_REQUIRES_AFFORDABILITY",
      "HALF_COST_NEUTRAL_SETTLEMENT",
      "LARGER_INITIAL_TERRITORY_SPAWN",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O06",
    traitIds: ["P39", "P01", "N07"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["DISTRIBUTED_PLAY", "POSITIONAL_CONTROL", "EXPANSION", "SPECIALIZATION", "INFRASTRUCTURE"],
      requiredAffordances: ["DISTRIBUTE_START", "MULTI_THEATER_ACCESS"],
      requiredCautions: ["SPLIT_FRONT_RISK", "ISOLATED_CORE_RISK", "EXPENSIVE_FAILURE"],
    },
    validationFocus: [
      "STRATEGIC_TWO_HALF_AREA_INFLUENCE_REGIONS",
      "TWO_EXACT_ORIGINS_ALL_MODES",
      "LARGER_TOTAL_INITIAL_TERRITORY_SPLIT_ACROSS_CORES",
      "ONE_GLOBAL_STARTING_POPULATION_POOL",
      "ONE_PER_STRUCTURE_TYPE_LIMIT_ACROSS_WHOLE_FACTION",
      "UNIQUE_STRUCTURE_PLACEMENT_ACROSS_TWO_CORES",
    ],
  },
  {
    originId: "O45",
    traitIds: ["P11", "P27", "N11"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["GROWTH", "FORTIFICATION", "INFRASTRUCTURE", "DETERRENCE", "POSITIONAL_CONTROL", "NAVAL_PROJECTION", "SPECIALIZATION"],
      requiredAffordances: ["INTERCEPT_OVER_LARGE_AREA", "PROTECT_HIGH_VALUE_ASSET", "DENY_AREA"],
      requiredCautions: ["COAST_DEPENDENCE", "SELF_GEOMETRY_RISK", "INFRASTRUCTURE_DEPENDENCE"],
    },
    validationFocus: [
      "POPULATION_UNLOCKED_ZERO_FFY_SAM_SLOTS",
      "SAM_ANTI_SHIP_CAPABILITY",
      "COASTAL_SAM_PLACEMENT_VALUE",
      "SAM_COVERAGE_ZEROES_FFY_EVENTS",
      "FREE_SAM_NETWORK_DEFENSE_VS_ECONOMY_GEOMETRY",
    ],
  },
  {
    originId: "O46",
    traitIds: ["P19", "P44", "N13"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["DECISIVE_FORCE", "DISTRIBUTED_PLAY", "EXPANSION", "ATTRITION", "TERRITORIAL_SHAPING", "POSITIONAL_CONTROL", "SIEGE"],
      requiredAffordances: ["CREATE_BREAKTHROUGH", "DENY_AREA", "SHAPE_TERRITORY", "CUT_CONNECTIVITY", "FORCE_ENEMY_RESPONSE"],
      requiredCautions: ["SPLIT_FRONT_RISK", "SELF_GEOMETRY_RISK"],
    },
    validationFocus: [
      "CONTACT_COUNT_OFFENSE_SCALING",
      "RADIOACTIVE_POPULATION_ATTACKS",
      "RADIOACTIVE_TERRITORY_SHAPING",
      "NO_BLIND_CONTACT_MAXIMIZATION",
      "HALF_TRANSPORT_POPULATION_DIES_ON_LANDING",
    ],
  },
  {
    originId: "O47",
    traitIds: ["P28", "P38", "N12", "N01"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["RAIDING", "ATTRITION", "GROWTH", "NAVAL_PROJECTION", "FORCE_PRESERVATION", "SACRIFICE"],
      requiredAffordances: ["PRESERVE_FORCE", "TRADE_GROUND_FOR_CASUALTIES", "LURE_OVEREXTENSION"],
      requiredCautions: [],
    },
    validationFocus: [
      "DESTROYED_ENEMY_TRANSPORT_POPULATION_BOUNTY",
      "AUTOMATIC_DEFENDER_SURVIVES_CAPTURE",
      "TRANSPORT_BOUNTY_SUPPORT_REMAINS_ACTIVE_WITHOUT_OWN_WARSHIPS",
      "WARSHIP_BUILD_UNAVAILABLE",
      "REDUCED_CITY_GROWTH_FORECAST",
    ],
  },
  {
    originId: "O48",
    traitIds: ["P52", "P02", "P36", "N02", "N12"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["ECONOMIC_COMPOUNDING", "EXPANSION", "SPECIALIZATION", "GROWTH", "FORCE_PRESERVATION"],
      requiredAffordances: ["SCALE_ECONOMY", "EXPAND_WITH_LOW_POPULATION", "SCALE_GROWTH", "EXPAND_CHEAPLY", "PRESERVE_FORCE"],
      requiredCautions: ["TERRAIN_DEPENDENCE"],
    },
    validationFocus: [
      "EMPTY_CAPACITY_PASSIVE_FFY",
      "WIDE_POPULATION_UTILIZATION_GROWTH",
      "HALF_COST_NEUTRAL_SETTLEMENT",
      "CAPACITY_ACQUISITION_USES_REAL_SETTLEMENT_COST",
      "UNDERPOPULATION_INCOME_VS_GROWTH_TRADEOFF",
      "PLAINS_OFFENSE_PENALTY",
      "WARSHIP_BUILD_UNAVAILABLE",
    ],
  },
  {
    originId: "O49",
    traitIds: ["P53", "P20", "P16", "N18", "N12"],
    requiredCombinationSupportIds: ["FALLOUT_ACQUISITION_INVERSION"],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["ECONOMIC_COMPOUNDING", "DETERRENCE", "INFRASTRUCTURE", "SPECIALIZATION", "ESCALATION", "EXPANSION", "POSITIONAL_CONTROL"],
      requiredAffordances: ["SCALE_ECONOMY", "BUILD_HIGH_LEVEL_INFRASTRUCTURE", "EXPLOIT_TERRAIN"],
      requiredCautions: ["INFRASTRUCTURE_DEPENDENCE", "SETUP_TIME"],
    },
    validationFocus: [
      "FREE_STARTING_MISSILE_SILO",
      "STARTING_READY_SILO_CHARGE_GENERATES_PASSIVE_FFY",
      "READY_CHARGE_INCOME_OPPORTUNITY_COST",
      "NON_FALLOUT_ACQUISITION_HALF_PROGRESS",
      "IGNORE_FALLOUT_CAPTURE_RESISTANCE",
      "FALLOUT_ACQUISITION_INVERSION",
      "WARSHIP_BUILD_UNAVAILABLE",
    ],
  },
  {
    originId: "O50",
    traitIds: ["P54"],
    requiredCombinationSupportIds: [],
    originSpecificSupport: null,
    profileAssertions: {
      requiredThemes: ["EXPANSION", "POSITIONAL_CONTROL", "SPECIALIZATION"],
      requiredAffordances: [],
      requiredCautions: ["OVEREXTENSION_RISK", "SELF_GEOMETRY_RISK"],
    },
    validationFocus: [
      "FIVE_POINT_STAR_INITIAL_TERRITORY_ALL_SPAWN_MODES",
      "SAME_FINAL_INITIAL_TERRITORY_QUOTA",
      "NO_EXTRA_STARTING_POPULATION",
      "NO_CAPTURE_SPEED_BONUS",
      "STAR_FRONTAGE_AND_EXPOSURE_FORECAST",
    ],
  },
] as const;
