import {
  EXPECTED_ORIGIN_TRAIT_IDS,
  ORIGIN_RULE_MANIFEST_BY_ID,
  originDynamicRuleProviders,
  type OriginCustomRuleDomain,
  type OriginTraitId,
} from "../src/core/rules/OriginRuleManifest";
import {
  canonicalRuleJson,
  type RuleCondition,
  type RuleContribution,
  type RuleScope,
} from "../src/core/rules/RuleComposition";

function scopeKey(scope: RuleScope): string {
  switch (scope.kind) {
    case "GLOBAL":
      return "GLOBAL";
    case "TERRAIN":
      return `TERRAIN:${scope.terrain}`;
    case "STRUCTURE":
      return `STRUCTURE:${scope.structure}`;
    case "UNIT":
      return `UNIT:${scope.unit}`;
    case "WEAPON":
      return `WEAPON:${scope.weapon}`;
    case "FFY_FAMILY":
      return `FFY:${scope.family}`;
  }
}

function conditionKey(condition: RuleCondition): string {
  switch (condition.kind) {
    case "SOURCE_TERRAIN_IS":
    case "TARGET_TERRAIN_IS":
    case "EVENT_TERRAIN_IS":
    case "BUILD_TERRAIN_IS":
      return `${condition.kind}:${condition.terrain}`;
    case "TARGET_HAS_FALLOUT":
    case "TARGET_LACKS_FALLOUT":
    case "PROJECTILE_IS_WARHEAD":
      return condition.kind;
    case "TARGET_UNIT_IS":
      return `${condition.kind}:${condition.unit}`;
    case "EVENT_INSIDE_FIELD":
    case "SOURCE_INSIDE_FIELD":
      return `${condition.kind}:${condition.field}`;
    case "STRUCTURE_ACQUISITION_PATH_IS":
      return `${condition.kind}:${condition.path}`;
  }
}

function conditionSetKey(contribution: RuleContribution): string {
  return [...(contribution.conditions ?? [])]
    .map(conditionKey)
    .sort()
    .join("&");
}

function valueKey(value: RuleContribution["value"]): string {
  if (value === undefined) return "";
  return Array.isArray(value) ? [...new Set(value)].sort().join(",") : String(value);
}

function descriptor(contribution: RuleContribution): string {
  return [
    contribution.axis,
    scopeKey(contribution.scope),
    contribution.stage,
    contribution.operator,
    contribution.valueUnit,
    valueKey(contribution.value),
    conditionSetKey(contribution),
  ].join("|");
}

const EXPECTED_PROJECTIONS: Readonly<
  Partial<Record<OriginTraitId, readonly string[]>>
> = {
  P01: ["INITIAL_TERRITORY_QUOTA|GLOBAL|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|1500|"],
  P02: ["POPULATION_GROWTH_UTILIZATION_PROFILE|GLOBAL|STRUCTURAL_PROFILE|STRUCTURAL_TRANSFORM|PROFILE_ID|ORIGIN_P02_30_70|"],
  P03: ["LAND_PRESSURE_SUPPRESSED_COMPONENTS|GLOBAL|COMPONENT_SUPPRESSION|SUPPRESS_COMPONENT|COMPONENT_SET|HOSTILE_FORT_DEFENSIVE_PRESSURE|"],
  P04: ["COUNTER_RESPONSE_EFFECTIVENESS|GLOBAL|FINAL_OVERRIDE|FINAL_OVERRIDE|RATIO|1|"],
  P06: ["UNIT_MOVEMENT_SPEED|UNIT:TRADE_SHIP|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|2500|"],
  P08: ["EXTERNAL_TRADE_WARTIME_MULTIPLIER|GLOBAL|BASE_REPLACEMENT|REPLACE_BASE|RATIO|1|"],
  P09: [
    "STRUCTURE_FIELD_COVERAGE_AREA|STRUCTURE:FORT|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|1000|",
    "STRUCTURE_PRESSURE_MAGNITUDE|STRUCTURE:FORT|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|900|",
    "STRUCTURE_BUILD_COST|STRUCTURE:FORT|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|-800|",
    "STRUCTURE_UPGRADE_COST|STRUCTURE:FORT|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|-800|",
  ],
  P10: ["WEAPON_PROJECTILE_SPEED|WEAPON:ALL|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|10000|PROJECTILE_IS_WARHEAD"],
  P11: [
    "STRUCTURE_BUILD_COST|STRUCTURE:SAM_LAUNCHER|TERMINAL|HARD_ZERO|NONE||",
    "STRUCTURE_UPGRADE_COST|STRUCTURE:SAM_LAUNCHER|TERMINAL|HARD_ZERO|NONE||",
  ],
  P12: ["UNIT_MOVEMENT_SPEED|UNIT:TRANSPORT_SHIP|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|2500|"],
  P13: ["TERRAIN_DEFENSIVE_PRESSURE|TERRAIN:MOUNTAIN|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|3300|"],
  P14: ["FFY_EVENT_YIELD|FFY:ALL|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|3300|EVENT_TERRAIN_IS:DESERT"],
  P15: ["TERRAIN_OFFENSIVE_PRESSURE|TERRAIN:HIGHLAND|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|3300|"],
  P16: ["ACQUISITION_SUPPRESSED_COMPONENTS|GLOBAL|COMPONENT_SUPPRESSION|SUPPRESS_COMPONENT|COMPONENT_SET|FALLOUT_ACQUISITION_RESISTANCE|"],
  P18: ["GLOBAL_OFFENSIVE_PRESSURE|GLOBAL|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|10000|SOURCE_INSIDE_FIELD:FORT"],
  P22: ["UNIT_MAX_RANK|UNIT:WARSHIP|ORIGIN_CAP|ADD_CAP|COUNT|2|"],
  P23: [
    "UNIT_ATTACK_RANGE|UNIT:WARSHIP|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|2000|",
    "UNIT_DAMAGE|UNIT:WARSHIP|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|2000|",
    "UNIT_MOVEMENT_SPEED|UNIT:WARSHIP|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|2000|",
    "UNIT_OWNERSHIP_CAP|UNIT:WARSHIP|ORIGIN_CAP|CAP_LIMIT|COUNT|1|",
  ],
  P24: ["FFY_EVENT_YIELD|FFY:ALL|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|2000|EVENT_INSIDE_FIELD:FORT"],
  P25: [
    "WEAPON_USE_PERMISSION|WEAPON:ATOM_BOMB|PERMISSION|PROHIBIT|NONE||",
    "WEAPON_USE_PERMISSION|WEAPON:MIRV|PERMISSION|PROHIBIT|NONE||",
    "WEAPON_BLAST_AREA|WEAPON:HYDROGEN_BOMB|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|5000|",
    "WEAPON_PURCHASE_FFY_COST|WEAPON:HYDROGEN_BOMB|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|5000|",
  ],
  P27: ["STRUCTURE_ATTACK_CAPABILITIES|STRUCTURE:SAM_LAUNCHER|CAPABILITY_ADD|ADD_CAPABILITY|CAPABILITY_SET|ATTACK_SHIPS|"],
  P30: [
    "UNIT_MOVEMENT_SPEED|UNIT:WARSHIP|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|5000|",
    "FFY_EVENT_YIELD|FFY:PIRACY|ORIGIN_SCALAR|MULTIPLY|BASIS_POINTS|30000|",
    "UNIT_ATTACK_CAPABILITIES|UNIT:WARSHIP|CAPABILITY_REMOVE|REMOVE_CAPABILITY|CAPABILITY_SET|NAVAL_GUNFIRE_AGAINST_SHIPS|",
  ],
  P31: [
    "STRUCTURE_REPAIR_RADIUS|STRUCTURE:PORT|CONTEXTUAL_SCALAR|MULTIPLY|BASIS_POINTS|20000|TARGET_UNIT_IS:WARSHIP",
    "STRUCTURE_REPAIR_RATE|STRUCTURE:PORT|CONTEXTUAL_SCALAR|MULTIPLY|BASIS_POINTS|15000|TARGET_UNIT_IS:WARSHIP",
  ],
  P32: ["UNIT_CHASSIS_PROFILE|UNIT:TRANSPORT_SHIP|STRUCTURAL_PROFILE|STRUCTURAL_TRANSFORM|PROFILE_ID|ARMORED_PORT_TRANSPORT|"],
  P34: [
    "FACTORY_TRAIN_EVENT_BASE_VALUE|STRUCTURE:FACTORY|CONTEXTUAL_SCALAR|MULTIPLY|BASIS_POINTS|15000|STRUCTURE_ACQUISITION_PATH_IS:CAPTURE_TRANSFER",
    "STRUCTURE_UNIT_CONSTRUCTION_WORK_RATE|STRUCTURE:FACTORY|CONTEXTUAL_SCALAR|MULTIPLY|BASIS_POINTS|15000|STRUCTURE_ACQUISITION_PATH_IS:CAPTURE_TRANSFER&TARGET_UNIT_IS:TANK",
    "STRUCTURE_REPAIR_RATE|STRUCTURE:FACTORY|CONTEXTUAL_SCALAR|MULTIPLY|BASIS_POINTS|15000|STRUCTURE_ACQUISITION_PATH_IS:CAPTURE_TRANSFER&TARGET_UNIT_IS:TANK",
    "STRUCTURE_REPAIR_RADIUS|STRUCTURE:FACTORY|FINAL_OVERRIDE|FINAL_OVERRIDE|CELLS|8|STRUCTURE_ACQUISITION_PATH_IS:CAPTURE_TRANSFER&TARGET_UNIT_IS:TANK",
    "STRUCTURE_UNIT_CONSTRUCTION_WORK_RATE|STRUCTURE:FACTORY|CONTEXTUAL_SCALAR|MULTIPLY|BASIS_POINTS|15000|STRUCTURE_ACQUISITION_PATH_IS:CAPTURE_TRANSFER&TARGET_UNIT_IS:HEAVY_ARTILLERY",
    "STRUCTURE_REPAIR_RATE|STRUCTURE:FACTORY|CONTEXTUAL_SCALAR|MULTIPLY|BASIS_POINTS|15000|STRUCTURE_ACQUISITION_PATH_IS:CAPTURE_TRANSFER&TARGET_UNIT_IS:HEAVY_ARTILLERY",
    "STRUCTURE_REPAIR_RADIUS|STRUCTURE:FACTORY|FINAL_OVERRIDE|FINAL_OVERRIDE|CELLS|8|STRUCTURE_ACQUISITION_PATH_IS:CAPTURE_TRANSFER&TARGET_UNIT_IS:HEAVY_ARTILLERY",
  ],
  P36: ["NEUTRAL_SETTLEMENT_POPULATION_COST|GLOBAL|BASE_REPLACEMENT|REPLACE_BASE|POPULATION|0.5|"],
  P37: ["TRANSPORT_EMBARK_COST|GLOBAL|ORIGIN_FLAT|ADD_FLAT|FFY|250|"],
  P39: ["SPAWN_PROFILE|GLOBAL|STRUCTURAL_PROFILE|STRUCTURAL_TRANSFORM|PROFILE_ID|SPLIT_TWO|"],
  P40: [
    "STRUCTURE_INTERCEPTION_RANGE|STRUCTURE:SAM_LAUNCHER|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|5000|",
    "STRUCTURE_CHARGE_CAPACITY|STRUCTURE:SAM_LAUNCHER|ORIGIN_CAP|CAP_LIMIT|COUNT|1|",
    "STRUCTURE_RECHARGE_TIME|STRUCTURE:SAM_LAUNCHER|ORIGIN_SCALAR|MULTIPLY|BASIS_POINTS|20000|",
  ],
  P42: [
    "UNIT_PURCHASE_FFY_COST|UNIT:WARSHIP|TERMINAL|HARD_ZERO|NONE||",
    "UNIT_PURCHASE_POPULATION_COST|UNIT:WARSHIP|BASE_REPLACEMENT|REPLACE_BASE|POPULATION|2000|",
    "UNIT_ATTACK_RANGE|UNIT:WARSHIP|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|-3300|",
  ],
  P43: ["UNIT_CHASSIS_PROFILE|UNIT:TANK|STRUCTURAL_PROFILE|STRUCTURAL_TRANSFORM|PROFILE_ID|HEAVY_ARTILLERY|"],
  P46: ["STRUCTURE_BUILD_PERMISSION|STRUCTURE:ALL|PERMISSION|ALLOW|NONE||BUILD_TERRAIN_IS:TUNDRA"],
  P48: ["TERRAIN_POPULATION_BEARING_PERMISSION|TERRAIN:SHALLOW_WATER|PERMISSION|ALLOW|NONE||"],
  P49: ["STRUCTURE_EFFECT_PROFILE|STRUCTURE:OBSERVATION_POST|STRUCTURAL_PROFILE|STRUCTURAL_TRANSFORM|PROFILE_ID|ENEMY_BLACKOUT|"],
  P54: ["SPAWN_FOOTPRINT_PROFILE|GLOBAL|STRUCTURAL_PROFILE|STRUCTURAL_TRANSFORM|PROFILE_ID|STAR|"],
  N01: ["CITY_GROWTH_CONTRIBUTION|STRUCTURE:CITY|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|-2000|"],
  N02: ["TERRAIN_OFFENSIVE_PRESSURE|TERRAIN:PLAINS|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|-2500|"],
  N03: ["TERRAIN_DEFENSIVE_PRESSURE|TERRAIN:DESERT|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|-3300|"],
  N04: ["FFY_EVENT_YIELD|FFY:ALL|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|-5000|EVENT_TERRAIN_IS:MOUNTAIN"],
  N05: ["FALLOUT_ACQUISITION_PERMISSION|GLOBAL|PERMISSION|PROHIBIT|NONE||"],
  N06: ["STRUCTURE_UPGRADE_PERMISSION|STRUCTURE:ALL|PERMISSION|PROHIBIT|NONE||"],
  N07: ["STRUCTURE_OWNERSHIP_CAP|STRUCTURE:ALL|ORIGIN_CAP|CAP_LIMIT|COUNT|1|"],
  N08: ["STRUCTURE_PRESSURE_MAGNITUDE|STRUCTURE:FORT|TERMINAL|HARD_ZERO|NONE||"],
  N09: ["STRUCTURE_BUILD_PERMISSION|STRUCTURE:FACTORY|PERMISSION|PROHIBIT|NONE||"],
  N10: ["STRUCTURE_FIELD_COVERAGE_AREA|STRUCTURE:FORT|ORIGIN_PERCENT|ADD_PERCENT|BASIS_POINTS|-2500|"],
  N11: ["FFY_EVENT_YIELD|FFY:ALL|TERMINAL|HARD_ZERO|NONE||EVENT_INSIDE_FIELD:SAM"],
  N12: ["UNIT_BUILD_PERMISSION|UNIT:WARSHIP|PERMISSION|PROHIBIT|NONE||"],
  N13: ["TRANSPORT_LANDING_SURVIVAL_FRACTION|GLOBAL|BASE_REPLACEMENT|REPLACE_BASE|RATIO|0.5|"],
  N15: ["TRANSPORT_EMBARK_COST|GLOBAL|ORIGIN_FLAT|ADD_FLAT|FFY|500|"],
  N18: ["ACQUISITION_PROGRESS|GLOBAL|CONTEXTUAL_SCALAR|MULTIPLY|BASIS_POINTS|5000|TARGET_LACKS_FALLOUT"],
};

const DYNAMIC_IDS = new Set<OriginTraitId>(["P11", "P17", "P19"]);
const MIXED_IDS = new Set<OriginTraitId>([
  "P02",
  "P31",
  "P34",
  "P36",
  "P37",
  "N13",
]);
const CUSTOM_IDS = new Set<OriginTraitId>([
  "P05",
  "P07",
  "P20",
  "P21",
  "P26",
  "P28",
  "P29",
  "P33",
  "P35",
  "P38",
  "P41",
  "P44",
  "P45",
  "P47",
  "P50",
  "P51",
  "P52",
  "P53",
  "N14",
  "N16",
  "N17",
]);

const EXPECTED_CUSTOM_DOMAINS: Readonly<
  Partial<Record<OriginTraitId, readonly OriginCustomRuleDomain[]>>
> = {
  P02: ["POPULATION_GROWTH_PROFILE_ANCHORS"],
  P05: ["STRUCTURE_CAPTURE_FFY_EVENT"],
  P07: ["FACTORY_DISPATCH_SCHEDULER"],
  P20: ["STARTING_STRUCTURE_GRANT"],
  P21: ["FIRST_STRUCTURE_PURCHASE_ZERO_FFY"],
  P26: ["MIRV_USE_ENTITLEMENT"],
  P28: ["TRANSPORT_DESTRUCTION_POPULATION_TRANSFER"],
  P29: ["WARSHIP_STRATEGIC_LAUNCHER"],
  P31: ["WARSHIP_OPERATIONAL_DURING_PORT_REPAIR"],
  P33: ["TRAIN_CITY_POPULATION_GRANT"],
  P34: ["FACTORY_TRAIN_DISPATCH_SNAPSHOT"],
  P35: ["RELINQUISHMENT_FALLOUT"],
  P36: ["SETTLEMENT_RESIDUAL_ACCOUNTING"],
  P37: ["LANDING_FORT_GRANT"],
  P38: ["AUTOMATIC_DEFENDER_SURVIVAL"],
  P41: ["DIRECT_LEVEL5_CITY_PURCHASE"],
  P44: ["RADIOACTIVE_ATTACK_AFTERSHOCK"],
  P45: ["FOREST_CONCEALMENT"],
  P47: ["MARSH_CAPTURE_POPULATION_PENALTY"],
  P50: ["MIRRORED_STRUCTURE_PRESSURE_FIELD"],
  P51: ["MIRRORED_STRUCTURE_PRESSURE_FIELD"],
  P52: ["PASSIVE_FFY_SOURCE"],
  P53: ["PASSIVE_FFY_SOURCE"],
  N13: ["TRANSPORT_LANDING_CASUALTY"],
  N14: ["TRADE_CAPTURE_VALUE"],
  N16: ["TRADE_CAPTURE_VALUE"],
  N17: ["STRUCTURE_CAPTURE_DISPOSITION"],
};

const EXPECTED_DYNAMIC = {
  P11: {
    id: "P11_SAM_OWNERSHIP_ENTITLEMENT",
    axis: "STRUCTURE_OWNERSHIP_CAP",
    scope: { kind: "STRUCTURE", structure: "SAM_LAUNCHER" },
    stage: "ORIGIN_CAP",
    operator: "CAP_LIMIT",
    sourceKind: "ORIGIN",
    sourceId: "P11",
    dependency: "PEAK_TOTAL_POPULATION",
    formula: { kind: "FLOOR_COUNT_PER_UNITS", unitsPerStep: 25_000 },
    operandKind: "INTEGER",
  },
  P17: {
    id: "P17_UPGRADE_DISCOUNT",
    axis: "STRUCTURE_UPGRADE_COST",
    scope: { kind: "STRUCTURE", structure: "ALL" },
    stage: "ORIGIN_SCALAR",
    operator: "MULTIPLY",
    sourceKind: "ORIGIN",
    sourceId: "P17",
    dependency: "OWNED_PERSISTENT_STRUCTURE_COUNT",
    formula: { kind: "RATIONAL_POWER", numerator: 99, denominator: 100 },
    operandKind: "RATIONAL",
  },
  P19: {
    id: "P19_CONTACT_OFFENSE",
    axis: "GLOBAL_OFFENSIVE_PRESSURE",
    scope: { kind: "GLOBAL" },
    stage: "CONTEXTUAL_PERCENT",
    operator: "ADD_PERCENT",
    sourceKind: "ORIGIN",
    sourceId: "P19",
    dependency: "TERRITORIAL_CONTACT_COUNT",
    formula: { kind: "BASIS_POINTS_PER_COUNT", bpPerUnit: 500 },
    operandKind: "BASIS_POINTS",
  },
} as const;

describe("Origin catalogue-to-manifest conformance", () => {
  it("matches the independently enumerated static projection for every trait", () => {
    for (const id of EXPECTED_ORIGIN_TRAIT_IDS) {
      const entry = ORIGIN_RULE_MANIFEST_BY_ID.get(id);
      expect(entry, id).toBeDefined();
      const expected = [...(EXPECTED_PROJECTIONS[id] ?? [])].sort();
      const actual = (entry?.contributions ?? []).map(descriptor).sort();
      expect(actual, id).toEqual(expected);
    }
  });

  it("matches the independent trait classification roster", () => {
    for (const id of EXPECTED_ORIGIN_TRAIT_IDS) {
      const entry = ORIGIN_RULE_MANIFEST_BY_ID.get(id);
      const expected = DYNAMIC_IDS.has(id)
        ? "DYNAMIC"
        : MIXED_IDS.has(id)
          ? "MIXED"
          : CUSTOM_IDS.has(id)
            ? "CUSTOM"
            : "DECLARATIVE";
      expect(entry?.classification, id).toBe(expected);
    }
  });

  it("matches every dynamic provider exactly", () => {
    for (const id of EXPECTED_ORIGIN_TRAIT_IDS) {
      const actual = originDynamicRuleProviders([id]);
      const expected = EXPECTED_DYNAMIC[id as keyof typeof EXPECTED_DYNAMIC];
      expect(actual, id).toEqual(expected === undefined ? [] : [expected]);
    }
  });

  it("matches every custom boundary exactly", () => {
    for (const id of EXPECTED_ORIGIN_TRAIT_IDS) {
      const actual = [...(ORIGIN_RULE_MANIFEST_BY_ID.get(id)?.customDomains ?? [])].sort();
      const expected = [...(EXPECTED_CUSTOM_DOMAINS[id] ?? [])].sort();
      expect(actual, id).toEqual(expected);
    }
  });

  it("keeps dynamic descriptors canonically serializable", () => {
    expect(
      originDynamicRuleProviders(["P11", "P17", "P19"])
        .map((provider) => canonicalRuleJson(provider))
        .sort(),
    ).toHaveLength(3);
  });
});
